### ISSUE TITLE
Provide an example how to get errors from asynchronous write API

### ISSUE THREAD

**Issue by fafnirbcrow** [influxdata/influxdb-client-go#102]
I was trying to upgrade my client from the v0.1.5 version we were previously using, however I am unsure how I am supposed to handle errors properly with the async writer functions. 

In https://github.com/influxdata/influxdb-client-go/blob/e9749eff443f60a61325700f3454961b92849b0b/write.go#L203 
If the service returns an error, it gets returned to a logger. and that is it. 

That logger seems to be an instance of https://github.com/influxdata/influxdb-client-go/blob/e9749eff443f60a61325700f3454961b92849b0b/internal/log/logger.go#L14
Which only does prints.

What is the expected method to identify and handle failures on data writes, and set up an automatic retry?

**Comment by vlastahajek** [comment]
@fafnirbcrow , WriteApi contains the [Errors()](https://github.com/influxdata/influxdb-client-go/blob/v1.1.0/write.go#L29) method, which returns channel for write errors.
You have to read this asynchronously, otherwise, it will block write procedure in case of an error occurs.

**Comment by fafnirbcrow** [comment]
I believe I see, so something like?

```
func handleErrors(e chan error){
	for i := range e {
		fmt.Println(i.Error())
	}
}

go handleErrors(WriteApi.Errors())
```
Since its a generic error object, how would we know which of the writes failed? Or should the entire batch be retried since it will overwrite in the db?

**Comment by vlastahajek** [comment]
You can't pair a received error and a batch now.  Batches are automatically retried on server overload (server responds with defined error codes).

Asynchronous write API best suits for writing frequent, nonprecious, data, such as telemetry, system metrics monitoring, weather sensing, etc.

You can use synchronous write API if you need control over write errors.

**Comment by fafnirbcrow** [comment]
That makes sense. Might I recommend that information be added to the documentation, including an example of error handling. It would be a useful inclusion for people like me who are trying to get a handle on flux still.

**Comment by vlastahajek** [comment]
Definitely. I was already planning to do so...
