### ISSUE TITLE
RetryInterval option default does not match documentation?

### ISSUE THREAD

**Issue by Tomcat-Engineering** [influxdata/influxdb-client-go#108]
The [comment](https://github.com/influxdata/influxdb-client-go/blob/master/options.go#L18) for the retry interval field of the Options struct says:

> Default retry interval in ms, if not sent by server. Default 30s

However, the [code in the `DefaultOptions` function](https://github.com/influxdata/influxdb-client-go/blob/master/options.go#L150) says `retryInterval: 1000`, which would only be one second.

Shouldn't they match?

**Comment by vlastahajek** [comment]
@Tomcat-Engineering, thanks for the issue. Default value 1s is correct, we will fix the comment.
