### ISSUE TITLE
Crash when iterating table with nil data returned?

### ISSUE THREAD

**Issue by srclosson** [influxdata/influxdb-client-go#110]
For some reason, the following scenario causes a crash:

Data returned from influxdb 2.0
```
	csvRows := []string{
		`#group,false,false,true,true,true,true,true,true,false,false`,
		`#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,string,string,double,dateTime:RFC3339`,
		`#default,mean,,,,,,,,,`,
		`,result,table,_start,_stop,_field,_measurement,cpu,host,_value,_time`,
		`,,0,2020-04-30T19:58:15.018029201Z,2020-04-30T20:58:15.018029201Z,usage_guest,cpu,cpu-total,084469dbdc49,,2020-04-30T19:58:20Z`,
		`,,0,2020-04-30T19:58:15.018029201Z,2020-04-30T20:58:15.018029201Z,usage_guest,cpu,cpu-total,084469dbdc49,0,2020-04-30T19:58:30Z`,
		`,,0,2020-04-30T19:58:15.018029201Z,2020-04-30T20:58:15.018029201Z,usage_guest,cpu,cpu-total,084469dbdc49,0,2020-04-30T19:58:40Z`,
		`,,0,2020-04-30T19:58:15.018029201Z,2020-04-30T20:58:15.018029201Z,usage_guest,cpu,cpu-total,084469dbdc49,0,2020-04-30T19:58:50Z`,
		`,,0,2020-04-30T19:58:15.018029201Z,2020-04-30T20:58:15.018029201Z,usage_guest,cpu,cpu-total,084469dbdc49,0,2020-04-30T19:59:00Z`,
	}
```

To reproduce, simply call 
		dr := ExecuteQuery(ctx, models.QueryModel{}, runner)

With the csv returned above and the error looks like this:

```
anic(0xbcd080, 0x134a4b0)
        /go1.14.2/src/runtime/panic.go:969 +0x166
github.com/influxdata/influxdb-client-go.(*FluxTableMetadata).Column(...)
        /go1.14.2/global/pkg/mod/github.com/influxdata/influxdb-client-go@v1.1.0/table.go:59
github.com/influxdata/influxdb-client-go.(*QueryTableResult).Next(0xc000246af0, 0xd15d00)
        /go1.14.2/global/pkg/mod/github.com/influxdata/influxdb-client-go@v1.1.0/query.go:307 +0x851
```

I've not looked into it with more detail, but I suspect it has something to do with the face that in the first line of data the value is <nil> or empty?

Let me know

**Comment by vlastahajek** [comment]
@srclosson, such crash has been already fixed in the master with [6ac10dcc](https://github.com/influxdata/influxdb-client-go/commit/6ac10dcc03d27c8ef8534fc84d1e90fff6f53d87). 
The flux result parser currently requires the `datatype` annotation as the first annotation row, and the `Query` method asks for it. 
How did you manage to get such a result?  
Do you query on your own and manually use `QueryTableResult` for parsing?
If yes, just make sure the `datatype` annotation is [the first among annotations](https://github.com/influxdata/influxdb-client-go/blob/master/query.go#L105)

**Comment by srclosson** [comment]
That did fix one problem, but there is another. The data was a query returned from influxdb 2.0. Notice the first line, the value column has no value. I expect this is because we used a grouping, and the first value was nil. 

The query looks like this:
```
from(bucket: "grafana")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```

The error I get now is the strconv.ParseFloat failed. 

Ideas?

**Comment by vlastahajek** [comment]
It's a bug. Unfortunately, empty values are not yet supported. You can work around this using the [fill](https://docs.influxdata.com/flux/v0.65/stdlib/built-in/transformations/fill/) function in Flux

**Comment by vlastahajek** [comment]
You can now try version master, where this is fixed.

**Comment by srclosson** [comment]
Will try it out.

**Comment by srclosson** [comment]
Confrimed @vlastahajek. Thank-you!

**Comment by vlastahajek** [comment]
Just to let you know, that custom order of annotations is now supported since #134. Only the _datatype_ annotation is required.
