### ISSUE TITLE
Parse the results of `buckets()`

### ISSUE THREAD

**Issue by ryantxu** [influxdata/influxdb-client-go#123]
When trying to parse the output of the query `buckets()` I get a failure on: 
![image](https://user-images.githubusercontent.com/705951/81857102-992e7800-9516-11ea-8a91-e1f6f40d819e.png)

Here is the csv:
```
#group,false,false,false,false,true,false,false
#datatype,string,long,string,string,string,string,long
#default,_result,,,,,,
,result,table,name,id,organizationID,retentionPolicy,retentionPeriod
,,0,grafana,059b46a59abab001,059b46a59abab000,,604800000000000
,,0,_tasks,059b46a59abab002,059b46a59abab000,,259200000000000
,,0,_monitoring,059b46a59abab003,059b46a59abab000,,604800000000000

```

**Comment by ryantxu** [comment]
ahh.  Seems the header order is out of sync.... if I make the headers: datatype,group,default it works

```
#datatype,string,long,string,string,string,string,long
#group,false,false,false,false,true,false,false
#default,_result,,,,,,
```
Unclear where/how this should be fixed... either:
* server sends them in the same order
* client accepts them in either order

**Comment by vlastahajek** [comment]
Yes, the QueryTableResult parser expects the `#datatype` annotation as the first row and the Query method takes care of this. 
How do you get the csv?

**Comment by jsternberg** [comment]
The flux CSV is meant to be parsed with the annotations in any order and we won't guarantee the order so the parser should be capable of parsing them in any order.

For helping with this specific issue right now, the annotations that are in the CSV will be returned in the same order as the entries in `dialect`. This seems to be constructed correctly for [DefaultDialect](https://github.com/influxdata/influxdb-client-go/blob/v1.1.0/query.go#L105) where the annotations are specified in the specific order that works with the client. As a temporary solution, you might be able to change your client to request the annotations in the same order.

**Comment by ryantxu** [comment]
After digging a bit more, we are not hitting this problem with a real environment -- just when saving files and loading them for tests.  In this case, we can manually reorder the headers and get the results needed

**Comment by vlastahajek** [comment]
Just to let you know, that custom order of annotations is now supported since #134. Only the _datatype_ annotation is required.
