### ISSUE TITLE
How to take backup using this API?

### ISSUE THREAD

**Issue by aggarwalanubhav** [influxdata/influxdb-client-go#127]
Hi, 
Could you please help me with how to take backup of a database using this particular API?

**Comment by vlastahajek** [comment]
The best way how to backup InfluxDB is by using the `influx` cmd tool. 
What is your use-case, that you need client lib for backing up DB?

**Comment by aggarwalanubhav** [comment]
I need to store the backup of my Influx Database to the cloud storage using Golang code.
