### ISSUE TITLE
`ping` is broken

### ISSUE THREAD

**Issue by zwpaper** [influxdata/influxdb-client-go#14]
I have checked the code, `ping` is simply `HTTP Get`ing the url: `ip:port/api/v2/ready`, and then a `401 {"code":"unauthorized","message":"unauthorized access"}` is returned.

When I try this in the browser after login, a `404 {"code":"not found","message":"path not found"}` is returned.

I also check the url: `ip:port/ready` is worked as expected without Auth.

Is this a client problem, or I should wait for the `api/v2/ready` implement in `influxdb`?

**Comment by docmerlin** [comment]
Looks like there is a bug in the 2.0 beta.  Thanks for bringing this to my attention.

**Comment by docmerlin** [comment]
@zwpaper the bug is mine, not in the beta.  Here is a fix for it.
