### ISSUE TITLE
Doesn't support array type?

### ISSUE THREAD

**Issue by strahe** [influxdata/influxdb-client-go#142]
Hi , 
I found that the introduction in the documentation supports array types: 
https://v2.docs.influxdata.com/v2.0/reference/flux/language/types/#array-types

but it seems that this library does not yet support:
https://github.com/influxdata/influxdb-client-go/blob/787ea0b9cd92fecfc66d8ddbc9498d7377c8c002/api/write/point.go#L128

**Comment by vlastahajek** [comment]
@strahe, [InfluxDB 2 write protocol](https://v2.docs.influxdata.com/v2.0/reference/syntax/line-protocol/#data-types-and-format) supports only basic primitive types.
