### ISSUE TITLE
Reduce the number of channels used in this library

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb-client-go#145]
https://github.com/influxdata/influxdb-client-go/blob/e21926f010e791568112e26785cdcc9a688d8490/api/write.go#L41-L49

https://github.com/influxdata/influxdb-client-go/blob/master/api/write.go#L174-L202

**Comment by andig** [comment]
@russorat I don't think that the number of channels is an actual issue, but the usage patterns seem a bit wild:

	if w.writeCh != nil {
		// Flush outstanding metrics
		w.Flush()
		w.bufferStop <- 1
		//wait for buffer proc
		<-w.doneCh
		close(w.bufferStop)
		close(w.bufferFlush)
		close(w.bufferCh)
		w.writeStop <- 1
		//wait for the write proc
		<-w.doneCh
		close(w.writeCh)
		close(w.writeStop)
		close(w.writeInfoCh)
		close(w.bufferInfoCh)
		w.bufferInfoCh = nil
		w.writeInfoCh = nil
		w.writeCh = nil
		w.writeStop = nil
		w.bufferFlush = nil
		w.bufferStop = nil
		if w.errCh != nil {
			close(w.errCh)
			w.errCh = nil
		}
	}

More so, idiomatic go would typically make a signalling channel of type `struct{}` and close it to signal.
