### ISSUE TITLE
Adding URL prefix to client

### ISSUE THREAD

**Issue by johnseekins** [influxdata/influxdb-client-go#149]
I'm currently trying to use this client to write to a VictoriaMetrics instance. They say that v2 API calls work correctly (https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#url-format), but every time I try to write using this client, it appears the client is ignoring the prefix I set.

For example, if I set `http://localhost:8480/insert/0:0/influx` as my serverUrl, this client appears to use `http://localhost:8480/api/v2/write` instead of `http://localhost:8480/insert/0:0/influx/api/v2/write` as I would expect.

Am I doing something wrong in the client? My actual instantiation:

```
    client := influxdb2.NewClientWithOptions(
        fmt.Sprintf("http://%v:%v/insert/0:0/influx", hostname, port),
        "",
        influxdb2.DefaultOptions().SetBatchSize(BatchSize),
    )
    writeApi := client.WriteApi("", "telegraf")
```

The error I receive:

```
Jul 09 14:34:06 <> vminsert-prod[6281]: 2020-07-09T14:34:06.206Z        warn        VictoriaMetrics/lib/httpserver/httpserver.go:204        unsupported path requested: "/api/v2/write"
```

A similar error I received using the v1 client:

```root@<>:~# journalctl -xeu victoriametrics-vminsert | grep "write/write"
Jul 08 22:42:20 <> vminsert-prod[6281]: 2020-07-08T22:42:20.815Z        warn        VictoriaMetrics/lib/httpserver/httpserver.go:204        unsupported path requested: "/insert/0:0/influx/write/write"
```

In this case, we can see it used the full path I had defined:

```
c, err := client.NewHTTPClient(client.HTTPConfig{
                Addr: fmt.Sprintf("http://%v:%v/insert/0:0/influx/write", hostname, port),
        })
```

 Which leads me to believe the client is stripping any url prefix.

**Comment by vlastahajek** [comment]
@johnseekins, thanks for posting the issue. Unfortunately, can confirm this a regression bug introduced in v1.1.0. If you use the client to write and query only, you can work around this by downgrading to v1.0.0

**Comment by johnseekins** [comment]
Downgrading to 1.0.0 I still see this error.

**Comment by vlastahajek** [comment]
Have you tried the V1 client with URL without the trailing  `/write`?
```go
c, err := client.NewHTTPClient(client.HTTPConfig{
     Addr: fmt.Sprintf("http://%v:%v/insert/0:0/influx", hostname, port),
})
```

**Comment by johnseekins** [comment]
Yes. That _does_ work (although it has some _huge_ memory leaks). I was hoping to use v2 'cause it seemed the more supported solution, but...

**Comment by vlastahajek** [comment]
And with the V2 client 1.0.0 you still see exactly the same error: `unsupported path requested: "/api/v2/write"`, or sth else? 1.0.0 correctly accepts server URL with path..

**Comment by johnseekins** [comment]
Exactly the same error, yes.

**Comment by johnseekins** [comment]
Oh no! I didn't test that correctly!

**Comment by johnseekins** [comment]
Never mind. 1.0.0 works perfectly fine. Thanks for the help.
