### ISSUE TITLE
is writeApi thread safe？

### ISSUE THREAD

**Issue by ciys** [influxdata/influxdb-client-go#150]
can i use the same writeApi in different goroutines？

**Comment by vlastahajek** [comment]
@ciys, yes you can. `writePoint` and `writeRecord` are asynchronous and thread-safe, so use them safely in different goroutines. However, there is a single writing routine,  you have to balance the number of wiriting routines.

**Comment by ciys** [comment]
@vlastahajek thank you

**Comment by SMerrony** [comment]
Could this be added to the docs please?
