### ISSUE TITLE
Cannot write to 1.6.4

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb-client-go#153]
After upgrading to 1.3.0 one user noticed that writes to 1.6.4 are broken (no user or password). DB is initialized like this:

	// InfluxDB v1 compatibility
	if token == "" {
		token = fmt.Sprintf("%s:%s", user, password)
	}

	client := influxdb2.NewClient(url, token)

	return &Influx{
		log:      log,
		client:   client,
		org:      org,
		database: database,
	}

Error is `[E]! Write error: 404 Not Found: 404 page not found` which looks like the path prefix error that influx2 shows when running the repl against influx1.

Any advise how to/ if running against 1.6.4 without user credentials should be supported?

**Comment by sranka** [comment]
You can use this client library with InfluxDB 2.x and InfluxDB 1.8+ (see [details](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibil)). For connecting to InfluxDB 1.7 or earlier instances, use the [influxdb1-go](https://github.com/influxdata/influxdb1-client) client library.
