### ISSUE TITLE
Getting a compilation error when running flux query with backslashes

### ISSUE THREAD

**Issue by taylanisikdemir** [influxdata/influxdb-client-go#158]
I'm using influxdb go client to run flux queries. I am having trouble filtering by a tag whose value is a windows file path with backslashes. 

Query:
```
"from(bucket: \"7446077d\")
|> range(start: 2020-07-19T01:18:45.417Z, stop: 2020-07-19T01:19:05.417Z)
|> filter(fn: (r) => r._measurement == \"agent.anomaly2\")
|> filter(fn: (r) => r._field == \"value\")
|> filter(fn: (r) => r.source == \"C:\\Program Files\\Data\\a.log\")"
```

Error: 
**invalid (): compilation failed: expected RPAREN, got EOF**

If I replace all backslashes with double backslashes it works fine. 
```
"from(bucket: \"7446077d\")
|> range(start: 2020-07-19T01:01:43.336Z, stop: 2020-07-19T01:02:03.336Z)
|> filter(fn: (r) => r._measurement == \"agent.anomaly2\")
|> filter(fn: (r) => r._field == \"value\")
|> filter(fn: (r) => r.source == \"C:\\\\Program Files\\\\Data\\\\a.log\")"
```

Questions:
1. Is this expected?
2. Is my workaround safe? 
3. Are there other characters we should be escaping to avoid similar query compilation issues?

Note: I'm using an older version of go client (from April) but I am able to repro this issue with latest version v1.4.0

**Comment by sranka** [comment]
Yes, it is expected, a backslash is escaped in a flux string and then also in a go string.  You can use golang's raw string literal to have less backslashes in a go string:
```
`from(bucket: "7446077d")
|> range(start: 2020-07-19T01:18:45.417Z, stop: 2020-07-19T01:19:05.417Z)
|> filter(fn: (r) => r._measurement == "agent.anomaly2")
|> filter(fn: (r) => r._field == "value")
|> filter(fn: (r) => r.source == "C:\\Program Files\\Data\\a.log")`
```

**Comment by taylanisikdemir** [comment]
The example queries I shared are generated with raw string literals by the way. It still requires escaping the backslashes twice.  Thanks for confirming the backslashes are escaped in a flux string as well as in a go string.

**Comment by vlastahajek** [comment]
Escaping special chars will be handled by the Query parameters feature, once implemented. The issue for this is #146.
