### ISSUE TITLE
Examples of batching BlockingAPI writes

### ISSUE THREAD

**Issue by johnseekins** [influxdata/influxdb-client-go#161]
__Proposal:__
Having control over failed batches would be very beneficial.

__Current behavior:__
Currently, the async client doesn't provide that (the error channel on sends an `error` object). The recommended path is to use the blocking client if you want to manage errors, but it isn't clear how we would batch these objects (except by creating the point objects at write time which might be more expensive).

__Desired behavior:__
Perhaps having an exported `Point` type so we could build a batch to write points.

```
writeAPI := client.WriteAPIBlocking("my-org","my-bucket")
var batch []Point
p := influxdb2.NewPoint("name", {"test": "test"}, {"test": 0}, time.Unix(0))
batch = append(batch, p)
err := writeAPI.WritePoint(context.Background(), batch)
        if err != nil {
            panic(err)
        }
```
__Alternatives considered:__
Getting the failed write data from the error channel in the async client.

__Use case:__
Handling retry logic or failure cases by shipping the failed data somewhere else to be re-processed while still having reasonable performance. Batching _vastly_ improves performance over writing one point at a time.

**Comment by johnseekins** [comment]
Of course, the (honestly more ideal) alternative is to be able to actually manage failed batches from the async writer in the error channel. This would be clearer code to manage and fairly easy to describe for newer users.

**Comment by vlastahajek** [comment]
@johnseekins, what you described as the desired behavior it is already possible. [Point](https://github.com/influxdata/influxdb-client-go/blob/master/api/write/point.go#L17) is already exported. You can have sth like:
```go
type writer struct {
	batch []*write.Point
	writeAPI api.WriteAPIBlocking
	batchSize int
}

func (w *writer) CurrentBatch() []*write.Point {
	return w.batch
}

func newWriter(writeAPI api.WriteAPIBlocking, batchSize int) *writer {
	return &writer{
		batch:     make([]*write.Point, 0, batchSize),
		writeAPI:  writeAPI,
		batchSize: batchSize,
	}
}

func (w *writer) write(ctx context.Context, p *write.Point) error {
	w.batch = append(w.batch, p)
	if len(w.batch) == w.batchSize {
		err := w.writeAPI.WritePoint(ctx, w.batch...)
		if err != nil {
			return err
		}
		w.batch = w.batch[:0]
	}
	return nil
}
```

Possibility to take control of failed batch of async WriteAPI makes sense, I will consider this.

**Comment by johnseekins** [comment]
That example is _exactly_ what I needed! Is there any chance you guys could put something like that in the docs? I was _close_ to working it out on my own, but there were a few small steps I hadn't taken.

**Comment by vlastahajek** [comment]
@johnseekins, where would like to see this example? In the readme or among the examples in the API doc?

**Comment by johnseekins** [comment]
I think the README would be the best place 'cause it's the most obvious. But either place is fine in my book. I would do whatever makes the most sense.
