### ISSUE TITLE
Create Retention Rules Through API

### ISSUE THREAD

**Issue by jessegeens** [influxdata/influxdb-client-go#167]
__Proposal:__ 
Currently, I do not see any way to create a `RetentionRules` in the API. The `RetentionRules` are stuck in the domain and there is no exposed way to create a new `RetentionRules`. 

__Current behavior:__
There is no way to create a `RetentionRules` in the go-client. 

__Desired behavior:__
A `CreateNewRetentionRules(duration int)` function in the `BucketsAPI`.

__Alternatives considered:__
None.

__Use case:__
This is very important for creating buckets through the go-client or updating an existing bucket's `RetentionRules`.

**Comment by vlastahajek** [comment]
@jessegeens , `domain` package contains generated code from the server swagger file. All structures and their field are public.
You can simply create `RetentionRules` via classic struct inializer: ` rr :=  domain.RetentionRule{EverySeconds: 3600 * 24}`, as can be seen in the [BucketsAPI example](https://pkg.go.dev/github.com/influxdata/influxdb-client-go@v1.4.0/api?tab=doc#example-BucketsAPI).

**Comment by jessegeens** [comment]
Ah yes I see, I looked over that. It sems to work. Thanks a lot!
