### ISSUE TITLE
save Chronograf graphs made via flux query

### ISSUE THREAD

**Issue by fxfactorial** [influxdata/influxdb-client-go#169]
I'd like this:

1. write the flux query in this client-go sdk
2. kick off the query to Chronograf
3. Save only the visualization, I don't need to recreate the whole dashboard, just the graph
4. Keep the single graph as I guess an SVG or png is fine too
5. be able to use this in whatever else business logic I have later

I don't see a way to do this now - I'd have to do a roundabout way with puppeteer i guess -

thank you

**Comment by vlastahajek** [comment]
@fxfactorial, this is an enhacement for InfluxDB 2 Dashboards API. You can programmatically create a dashboard and a cell, however, AFAIK, there is no view to get rendered cell view.
