### ISSUE TITLE
Using tasks 

### ISSUE THREAD

**Issue by fxfactorial** [influxdata/influxdb-client-go#170]
I see in the domain package the autogenerated `domain.TaskCreateRequest` but there is no corresponding handler in `api` package. So there is no way currently to programmatically make a task, control it, from this library?

**Comment by vlastahajek** [comment]
@fxfactorial, the TasksAPI is in the plan for implementation and it will be added in the some of next releases.
Unfortunately, you can not implement the domain calls using this library on your own as the generated client depends on the HTTP service which is internal now. It will be made public in the next release.

**Comment by vlastahajek** [comment]
#181 added the ability to create custom server API calls using generated code. There is also an example [how to create task](https://github.com/influxdata/influxdb-client-go/blob/master/examples_test.go#L28).
