### ISSUE TITLE
Documentation consistency issue on write client

### ISSUE THREAD

**Issue by Jamesits** [influxdata/influxdb-client-go#171]
In the [Getting Started with the InfluxDB Go Client](https://www.influxdata.com/blog/getting-started-with-the-influxdb-go-client/) article, there is:

> WriteApiBlocking(): returns the synchronous, blocking, write client. **It provides implicit batching.** Batches are generated from the given number of points.

While in [the REAEME.md of this project](https://github.com/influxdata/influxdb-client-go/blame/c62c843ea90fc2367c597088d4d29baca150b1f5/README.md#L239):

> Blocking write client writes given point(s) synchronously. **It doesn't have implicit batching.** Batch is created from given set of points.

I guess one of them should be changed.

**Comment by vlastahajek** [comment]
@Jamesitsm thanks for posting the issue. The blog post needs to be corrected. I've contacted the author.

**Comment by vlastahajek** [comment]
The blog has been finally fixed. Thanks for pointing to this.
