### ISSUE TITLE
cannot query all data with "influxdb-client-go" but "influxdb1-client" can

### ISSUE THREAD

**Issue by ciys** [influxdata/influxdb-client-go#172]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. first "create database telegraf " and then "create retention policy umcs_policy on telegraf duration 1d replication 1 default"
2. write some data to telegraf with the api of "influxdb-client-go" write point, and "influxdb-client-go" query all data.
3. two days later, insert some new data."influxdb-client-go" cannot query all data,but "influx cli" and "influxdb1-client" can.After restart the influxdb,the "influxdb-client-go" can too.
4.  "influxdb-client-go" with flux ,"influxdb1-client" and  "influx cli" are both with InfluxQL

__Expected behavior:__
query all data

__Actual behavior:__
query part data

__Specifications:__
 - Client Version:1.1.0
 - InfluxDB Version:1.8.0
 - Platform:centos

**Comment by ciys** [comment]
i change client version to the latest 1.4.0 still not work

**Comment by vlastahajek** [comment]
@ciys, could you, please, write your flux query?

**Comment by ciys** [comment]
measurement：module_status
tag:module,ip
field:status

flux query:
`from(bucket:"telegraf")
     |>range(start:-1d)
     |>filter(fn: (r) => r._measurement == "module_status")
     |>group(columns:["module"])
     |>sort(columns:["_time",desc:true])
     |>limit(n:1)`

i think flux query is ok,because i do nothing but only restart the influxdb,it can query all data

**Comment by vlastahajek** [comment]
Your steps list contains item:
>  two days later, insert some new data."influxdb-client-go" cannot query all data,but "influx cli" and "influxdb1-client" can.After restart the influxdb,the "influxdb-client-go" can too.

However, your query limits time range only for last 24h: `|>range(start:-1d)`. Flux [needs exact time range](https://docs.influxdata.com/flux/v0.65/introduction/getting-started/query-influxdb/#2-specify-a-time-range).

**Comment by ciys** [comment]
@vlastahajek i think 24h is too long to query my data.Maybe my description is not accurate enough.

> two days later, insert some new data."influxdb-client-go" cannot query all data,but "influx cli" and "influxdb1-client" can.After restart the influxdb,the "influxdb-client-go" can too.
first insert new data and then query ,an interval of ten minutes,so 24h is enough.If i set wrong time range,why it is ok after restart the influxdb?

**Comment by ciys** [comment]
@vlastahajek

>  |>range(start:2020-08-11T01:36:30.444Z,stop:2020-08-11T09:36:30.444Z)

still not work,and the date time is between 2020-08-11T05:36:30.444Z to 2020-08-11T05:36:33.596Z

**Comment by ciys** [comment]
i think it is not client bug,i try my query in chronograf still not work.but other measurement is ok,only the "module_status"

**Comment by vlastahajek** [comment]
Can show the query for InfluxQL and also query result set?

**Comment by ciys** [comment]
use telegraf
select * from module_status
![微信图片_20200811161730](https://user-images.githubusercontent.com/3349701/89874541-8e0ae700-dbee-11ea-95c5-16f2712dda77.jpg)
and flux only can query "quot_service" only.

**Comment by vlastahajek** [comment]
If you modify flux query to be as simple as it can, e.g.:
```flux
from(bucket:"telegraf")
|>range(start:-1d)
|>filter(fn: (r) => r._measurement == "module_status")
```
Do you see what you need? Flux groups result data by all tags by default. So, for the result set as shown above you will get 4 tables.
If you would like to see all results in a single table, use [influxFieldsAsCols()](https://docs.influxdata.com/flux/v0.65/stdlib/built-in/transformations/influxfieldsascols/)
