### ISSUE TITLE
can't assign requested address

### ISSUE THREAD

**Issue by saxoned** [influxdata/influxdb-client-go#177]
dial tcp 192.168.200.21:9999: connect: can't assign requested address

assign to many tcp address when use the write api, add conn pool into it?

**Comment by vlastahajek** [comment]
HTTP connections should be reused. How many goroutines are writing data? Can you show the code using WriteAPI?

**Comment by saxoned** [comment]
**hi, this is my code**
```
writeAPI := NewInfluxClient().WriteAPIBlocking("test", "matrix_test")
for id := 0; id < 50; id++ {
go func(){
tags:=?
files:=?
createdAt:=?
p := influxdb2.NewPoint("sensorData", tags, fields, createdAt)

writeApi.WritePoint(context.Background(), p)

}
}
```

**Comment by vlastahajek** [comment]
Thanks. Does it mean you got the error after writing just 50 points? 
Could you, please, show netstat output about connections state after you get the error?

**Comment by saxoned** [comment]
sorry, i have modified the code like this

**Comment by saxoned** [comment]
```
	doCancel := func() {
		// The second way in the func comment above:
		close(cancel)
		// The first way, used only for RoundTripper
		// implementations written before Go 1.5 or Go 1.6.
		type canceler interface{ CancelRequest(*Request) }
		if v, ok := rt.(canceler); ok {
			v.CancelRequest(req)
		}
	}


go func() {
		select {
		case <-initialReqCancel:
			doCancel()
			timer.Stop()
		case <-timer.C:
			timedOut.setTrue()
			doCancel()
		case <-stopTimerCh:
			timer.Stop()
		}
	}()
```
**I found the code in http/client.go,the code means the http request with a new goroutine for handle doCancel(), so  the writeApi.WritePoint will open a new groutine for handle it?if so, I think I see!**

**Comment by vlastahajek** [comment]
Generally, using WriteAPIBlocking for writing single points in a fast manner is not efficient.  If your intention is to write many ( tens) points per second, I would recommend using async WriteAPI, which implicitly batches points.

The code above is about handling cancelation. WriteAPIs in this library handle that as well.

**Comment by saxoned** [comment]
thanks very much ,you fixed my question

**Comment by vlastahajek** [comment]
However, your code is not wrong. So, if you got that error, it means there is probably an issue. Could you, please, reproduce the issue and show system connections status using the `netstat` or similar tools (`ss`)?

**Comment by saxoned** [comment]
```
➜  ~ netstat -na|wc -l 
     537
➜  ~ netstat -na|wc -l 
    5227
➜  ~ netstat -na|wc -l 
    6372
➜  ~ netstat -na|wc -l 
    8825
➜  ~ netstat -na|wc -l 
   11058
➜  ~ netstat -na|wc -l 
   16888
➜  ~ netstat -na|wc -l 
   16888

```
when the conn count is 16888,i got that error

**Comment by saxoned** [comment]
```
package main

import (
	"context"
	influxdb2 "github.com/influxdata/influxdb-client-go"
	"github.com/influxdata/influxdb-client-go/api"
	"github.com/sirupsen/logrus"
	"math/rand"
	"strconv"
	"time"
)

func main() {

	forever := make(chan bool)


	writeAPI := NewInfluxClient().WriteAPIBlocking("test", "matrix_test")
	for id := 0; id < clientTotal; id++ {
		go func(id int) {
			createdAt := time.Now().Add(-time.Hour * 24 * 365 * 3)
			N := 1

			for i := 0; i < recordTotalOfOneClient; i++ {
				sn := GetRandomSn()
				tags := map[string]string{"sn": sn}
				fields := GetRandomValues()


			
				WriteToInfluxDB(writeAPI, tags, fields, createdAt)

				mongoData := fields
				mongoData["sn"] = sn
				mongoData["createdAt"] = createdAt.UnixNano()


				createdAt = createdAt.Add(time.Duration(GetRandomNum())* time.Millisecond)
				if N%10 == 0 {
					logrus.Infof("client【%d】:now writing %d 【%v】", id, N, createdAt)
				}
				N++

			}

		}(id)
	}
	<-forever

}

func WriteToInfluxDB(writeApi api.WriteAPIBlocking, tags map[string]string, fields map[string]interface{}, createdAt time.Time) {
	p := influxdb2.NewPoint("sensorData", tags, fields, createdAt)
	writeApi.WritePoint( context.Background(),p)

}


func NewInfluxClient() influxdb2.Client {
	influxdb2.NewClientWithOptions("","",influxdb2.DefaultOptions())
	return influxdb2.NewClient("your address", "my token")

}



func GetRandomSn() string {
	rand.Seed(time.Now().UnixNano())
	return strconv.Itoa(rand.Intn(3000) + 10000000)
}

func GetRandomNum() int  {
	rand.Seed(time.Now().UnixNano())
	return rand.Intn(30)+200

}

func GetRandomValues() map[string]interface{} {
	rand.Seed(time.Now().UnixNano())
	values := make(map[string]interface{})
	sensorType := rand.Intn(4)
	switch sensorType {
	case meter:
		values["current"] = GetRandomValue()
		values["voltage"] = GetRandomValue()
	case temperature:
		values["temperature"] = GetRandomValue()
		values["humidity"] = GetRandomValue()
	case current:
		values["current"] = GetRandomValue()
		values["temperature"] = GetRandomValue()
	case voltage:
		values["voltage"] = GetRandomValue()
		values["current"] = GetRandomValue()
		values["temperature"] = GetRandomValue()

	}
	return values
}

func GetRandomValue() float32 {
	rand.Seed(time.Now().UnixNano())

	return rand.Float32() + float32(rand.Intn(20)+30)
}

const recordTotalOfOneClient= 30000000
const clientTotal = 50

const (
	meter = iota
	temperature
	current
	voltage
)

```

this is my test code

**Comment by bugfix4u** [comment]
I am also seeing this error after a few days of running my program. I have a daemon process that wakes once a day and processes a lot of logs to write points to the DB. My program can be processing several file asynchronously, but each routine creates a client, creates an async writer then writes all the point for that file, which can be 100's of thousands, then it closes the writer and closes the client. The flush time is 1s or 5000 points. After about three days of running I start getting "dial tcp xxx.xxx.xxx.xxx:8086: connect: cannot assign requested address" error on each write attempt.

I was creating a single client for the entire parsing run of the logs and only creating/closing the writer as I processed each file, and this seem to work fine, but there seems to be a memory leak that was causing the app to consume large amounts of memory, which is why I changed to creating the client and writing for each file I parsed. I think the memory issue I was seeing may be fixed by "WriteAPI Out Of Memory #163"

**Comment by vlastahajek** [comment]
As advised in [the answer for the same issue](https://stackoverflow.com/questions/39813587/go-client-program-generates-a-lot-a-sockets-in-time-wait-state), try to set the `MaxIdleConnsPerHost` property of the transport. The version in the master (which will be released today) [adds setting a custom HTTP client](https://github.com/influxdata/influxdb-client-go/blob/master/options.go#L141-L150), which in turn enables setting custom transport options:
```go
client:= influxdb2.NewClientWithOptions(InfluxDB2Url, *token, influxdb2.DefaultOptions().
		SetBatchSize(5000).
		SetLogLevel(*debugLevel).
		SetRetryInterval(1000).
		SetFlushInterval(1000).
		SetHTTPClient(&http.Client{
		Timeout: time.Second * time.Duration(20),
		Transport: &http.Transport{
			DialContext: (&net.Dialer{
				Timeout: 5 * time.Second,
			}).DialContext,
			TLSHandshakeTimeout: 5 * time.Second,
			MaxIdleConns: *threadsCount,
			MaxIdleConnsPerHost: *threadsCount,
		},
	}))
```
I was able to reproduce the issue as @saxoned described using WriteAPIBlocking and writing single points quickly and this setting fixes this problem.
However, Writing point per point quickly is not a good practice, either batch them, e.g. [using a wrapper](https://github.com/influxdata/influxdb-client-go/issues/161) or, rather, employ async WriteAPI.

WriteAPIBlocking is intended for writing less frequent data, e.g. from weather sensors.

**Comment by saxoned** [comment]
thank you for your answer，I think I would use the async writeApi, it will automatic batch processing of my data

**Comment by bugfix4u** [comment]
Thanks, I looked for a SetHTTPClient function and must have missed it. I figured setting the max idle connections would help this.

**Comment by saxoned** [comment]
> thank you for your answer，my backend server will receive many data per minute,i think I would use the async writeApi, it will automatic batch processing of my data @vlastahajek ,thanks influxdb
> I have tested 660 million pieces of data, the influxdb used 32G Hard drive capacity ，but the mongodb was 47G
> I query the sensor data by sn and createdAt(one day of the last three years),this was the test result
> 
> db	index	query time
> influxdb	sn+createdAt	0.35s
> mongodb	none	timeout
> mongodb	createdAt	181.21s
> mongodb	sn+createdAt	76.92s
