### ISSUE TITLE
add  deleteApi and updateapi

### ISSUE THREAD

**Issue by saxoned** [influxdata/influxdb-client-go#178]
now, due to the influxdb has not deleteApi and updateApi,
i use two types databases for data persistence ,
mongodb for some data that need to update and delete like orderinfo ,
influxdb for store my time series data  , 
whether has such a plan for solve the situation

**Comment by vlastahajek** [comment]
Which InfluxDB version do you use?
Generally, updates are done by writing data with the same tags and the same timestamp.
InfluxDB 1.x uses InfluxQL query API to database management and deletes, this is not supported by this library.
InfluxDB 2 has the DeleteAPI and [it is supported by this library](https://pkg.go.dev/github.com/influxdata/influxdb-client-go@v1.4.0/api?tab=doc#DeleteAPI).

**Comment by saxoned** [comment]
I use the influxdb2 ,thank you so much, you are a good man/woman
