### ISSUE TITLE
Client does not work with compatibility endpoints

### ISSUE THREAD

**Issue by coussej** [influxdata/influxdb-client-go#182]
Using the then endpoint URL /api/v2 as described in the documentation does not work:
```
package main

import (
	"context"
	"fmt"

	influxdb2 "github.com/influxdata/influxdb-client-go"
)

func main() {

	client := influxdb2.NewClient("https://demo.factry.io:8086/api/v2", "token_here")
	queryAPI := client.QueryAPI("factry")

	query := `from(bucket: "simulation_tanksystem")
							|> range(start: -2h, stop:-30m)
							|> filter(fn: (r) => r._measurement == "WP1_fill_level")
							|> aggregateWindow(every: 30s, timeSrc: "_start", fn: mean, createEmpty:false)`

	// get parser flux query result
	_, err := queryAPI.Query(context.Background(), query)
	if err != nil {
		fmt.Println(err)
	}

}
```
this returns 404 not found. No using /api/v2, so just `influxdb2.NewClient("https://demo.factry.io:8086", "token_here")`, executes the query successfully. This behaviour is inconsistent with what both the influxdb 1.8 docs and this client's docs mention.

**Comment by vlastahajek** [comment]
Using base server URL, e.g. `influxdb2.NewClient("https://demo.factry.io:8086", "token_here")`, is the right and [documented way](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility) how to connect to InfluxDB 1.8 using this client. Please, don't mix this with docs on how to create API calls using raw HTTP clients.

Where have you seen a recommendation for this client to use /api/v2 suffix?

**Comment by coussej** [comment]
You're right, it doesn't say to use the api/v2. But, apart from the example, the link you refer to doesn't mention to use the base URL explicitly. It also links to the influxDB docs, where they say the compatibilty endpoint is /api/v2, and I know as a fact I'm not the only one confused by this :-)

Maybe to avoid confusion it better to mention this explicitly? 

Anyway, thanks for your response!

**Comment by coussej** [comment]
https://github.com/influxdata/influxdb-client-go/compare/master...coussej:patch-1 ;-)

**Comment by coussej** [comment]
https://github.com/influxdata/influxdb-client-go/pull/188
