### ISSUE TITLE
2.0: go.mod invalid

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb-client-go#186]
After latest release go.mod seems invalid:

```
❯ go get github.com/influxdata/influxdb-client-go@v2.0.0
go get github.com/influxdata/influxdb-client-go@v2.0.0: github.com/influxdata/influxdb-client-go@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

I assume you'll need to add a /v2 to the go.mod path

**Comment by aknuds1** [comment]
I was just going to report the same thing.

**Comment by aknuds1** [comment]
We solved it by using a Git revision reference: 

```
github.com/influxdata/influxdb-client-go v0.0.0-20200814135139-d68836272a45
```

**Comment by andig** [comment]
Interesting that works. It shouldn't as the version path would still be wrong at import time...

**Comment by aknuds1** [comment]
> Interesting that works. It shouldn't as the version path would still be wrong at import time as one should require it as /v2...

Doesn't seem to matter if you use a Git revision.

**Comment by vlastahajek** [comment]
Guys, I'm very sorry for this trouble. I haven't known that Go has such a complicated way for upgrading major versions. I'm preparing the fix..
