### ISSUE TITLE
Update the default port to be 8086 instead of 9999

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb-client-go#195]
As we move to ga oss 2.0, we will need to swap the port number from 9999 to 8086

**Comment by vlastahajek** [comment]
@russ, when the change of port will happen? This change needs to be synced with an InfluxDB release to avoid user confusion.

**Comment by russorat** [comment]
pr for the change to influxdb: https://github.com/influxdata/influxdb/pull/19494
