### ISSUE TITLE
Create a new database via influxdb-client-go

### ISSUE THREAD

**Issue by mong0520** [influxdata/influxdb-client-go#198]
__Proposal:__
Create a new database via influxdb-client-go

__Current behavior:__
Unable to create a new database via influxdb-client-go

__Desired behavior:__
Able to create a new database via influxdb-client-go

__Alternatives considered:__
n/a

__Use case:__
In some use cases, I'd like to separate different database for different customer/user, like `create database DB_user1`, `create database DB_user2`, ... so I'd like to use this lib to create them instead of using influxdb shell for that.

**Comment by vlastahajek** [comment]
@mong0520, this library mainly supports for InfluxDB 2. InfluxDB 1 is supported via [forward compatibility API](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility). 
InfluxQL and associated expressions are not supported. Use [influxdb1-client](https://github.com/influxdata/influxdb1-client) for that.
