### ISSUE TITLE
Issue with creating retention policy using domain package client (influxdb-client-go/v2/domain)

### ISSUE THREAD

**Issue by stonnu** [influxdata/influxdb-client-go#199]
Hi, I am currently trying to use the `domain.NewClientWithResponses()` with the `HTTPService()` in my influxdb go client in order to create new retention policies. From what I understand, we can create a retention policy by hitting the /query HTTP endpoint and making a POST request. (https://docs.influxdata.com/influxdb/v1.8/tools/api/#query-http-endpoint)

I looked through the client generated go code and saw a struct for `InfluxQLQuery`, and I tried creating the query I wanted (e.g. "CREATE RETENTION POLICY four_weeks ON database DURATION 4w REPLICATION 1") and setting the query `type` as "influxql", and then calling `PostQueryWithResponse`. However, I am getting an error `"unknown query type: influxql"`.

Am I incorrectly using the domain package / API to make the POST request, or am I misunderstanding how it works entirely? If so, how should I create my request to create a retention policy and which client method should I be using instead? Thank you so much in advance! And please let me know if I can clarify more on anything I've said above.

**Comment by vlastahajek** [comment]
@stonnu, this library primarily supports InfluxDB 2. InfluxDB 1 is only supported via [forward compatibility API](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility).
InfluxQL and associated expressions are not supported. Use [influxdb1-client](https://github.com/influxdata/influxdb1-client) for that, please.

**Comment by stonnu** [comment]
@vlastahajek Oh I see, so just to double check, there is no way to use the new InfluxDB 2 library to create a retention policy?

**Comment by vlastahajek** [comment]
Using this client library is not possible to call the `/write` and `/query` endpoints currently. However, if you don't want to use another library you can simply call `/query` endpoint with an InfluxQL command using HTTP API.
