### ISSUE TITLE
URL inconsistency in example 

### ISSUE THREAD

**Issue by bckeene** [influxdata/influxdb-client-go#202]
Under https://github.com/influxdata/influxdb-client-go#basic-example, the import statement references `"github.com/influxdata/influxdb-client-go/v2"`. Should this be `https://github.com/influxdata/influxdb-client-go`?

**Comment by vlastahajek** [comment]
@bckeene,  thanks for posting the issue. The _github.com/influxdata/influxdb-client-go/v2_ is the right URL. The issue is in the paragraph above, where the _import statement, _github.com/influxdata/influxdb-client-go_, is wrong.

**Comment by vlastahajek** [comment]
Fixed in the v2.1.0
