### ISSUE TITLE
Question: How to continuously run queries in InfluxDB

### ISSUE THREAD

**Issue by amartya-dev** [influxdata/influxdb-client-go#207]
I recently stumbled upon this great repo, I just wanted to know if it is possible to use influxDB for the following use case:

- I am continuously reading data from a client using gRPC and pushing that data in influxDB
- I need to be able to have another RPC which can continuously query influxDB and keep streaming the values till the other clients are adding them if there are no values added for a threshold of say 10 minutes, then I should be able to break the stream.

Is it possible to do this with the current client implementation? If yes, where can I find an example?

**Comment by amartya-dev** [comment]
I figured it out so I am closing this issue, although adding pointers here just in case someone gets stuck here again:

The 
```go
result.TableChanged()
```
automatically does this for us, it keeps checking if there are any new entries in the table and starts streaming them, an example of the implementation will be:
```go
func (s *myServer) Monitor(<your_message_class>, stream <response_class>) error {
	queryAPI := dbConnection.QueryAPI("")

	// Keep checking for last minute's records and keep adding them to stream, break when there are no records in
	// the last minute
	result, err := queryAPI.Query(
		context.Background(), `from(bucket:"test")|> range(start: -1m)`)
	totalRecords := 0
	if err == nil {
		for result.Next() {
			if result.TableChanged() {
				grpcLog.Infof("table: %s\n", result.TableMetadata().String())
			}
			totalRecords++
			grpcLog.Infof("row: %s\n", result.Record().String())

			// Send the response to the stream
			if streamErr := stream.Send(
                            // Send your request here
			}); streamErr != nil {
				return streamErr
			}
		}
		if result.Err() != nil {
			grpclog.Infof("Query error: %s\n", result.Err().Error())
		}
	} else {
		grpclog.Errorf("Query error: %s\n", err.Error())
	}
	fmt.Printf("Got %v records", totalRecords)

	// Return nil if there is no error after whole execution
	return nil
}
```

**Comment by vlastahajek** [comment]
@amartya-dev, as you have already figured out, you have to just call `Query` periodically.
The `TableChanged()` just informs about the new group key among data.

**Comment by amartya-dev** [comment]
Yes thank you. This is a really awesome feature
