### ISSUE TITLE
Unsynchronized WriteAPIBlocking.Write* functions

### ISSUE THREAD

**Issue by vlastahajek** [influxdata/influxdb-client-go#208]
`WriteAPIBlocking.WritePoint` and `WriteAPIBlocking.WriteRecord` must ensure synchronized calling of  `write.Service.HandleWrite`

**Comment by ridwankustanto** [comment]
I have problem with writing data to influxdb, there is no error anywhere, but I checked the bucket, the data not sent. Is it because of this bug? I tried with `WriteAPIBlocking.WritePoint` and `WriteAPI.WritePoint` but no luck.

**Comment by vlastahajek** [comment]
@ridwankustanto, your problem is most probably somewhere else.  The race condition here could happen in the specific condition when data is written by multiple goroutines and the server is overloaded and returns an error.

How do you check the data is written?
Do you write data with a timestamp?

**Comment by ridwankustanto** [comment]
Hi @vlastahajek, ohh I see. I checked the error with both ways (asynchronously and synchronously), I got nothing. But I guess I found the problem and I fixed it. It was my mistake with the timestamp. Thanks for reminding me about that!
