### ISSUE TITLE
Retention_policy not responding

### ISSUE THREAD

**Issue by FredPi17** [influxdata/influxdb-client-go#211]
__Steps to reproduce:__
We created two terraform providers that communicates with this go client. First is for the [onboarding configuration](https://github.com/lancey-energy-storage/terraform-provider-influxdb-v2-onboarding) and second is to create resources like buckets or authorization [here](https://github.com/lancey-energy-storage/terraform-provider-influxdb-v2). 
These providers just get actual configurations of this go client and convert commands to be usable with terraform.  
List the minimal actions needed to reproduce the behavior.

1. create the terraform configuration like below
```hcl
resource "influxdbv2_bucket" "forecasts" {
  depends_on = [influxdbv2-onboarding_setup.setup]
  name = "forecasts"
  org_id = influxdbv2-onboarding_setup.setup.org_id
  rp = "2h"
  retention_rules {
    every_seconds = 1
  }
}
```
2. terraform apply

__Expected behavior:__
I should have a new bucket created in the influxdb instance.

__Actual behavior:__
The influxdb api returns that the retention policy must to be at least 1h.

__Specifications:__
 - Client Version: v2.2.0 (latest)
 - InfluxDB Version: 2.0.0.rc
 - Platform: Linux / Digitalocean

So, what is the actual error on this client. Is it just not updated with the latest version of Influxdb, or else ? 

Thank's in advance !

**Comment by vlastahajek** [comment]
@FredPi17, you've probably figured out this is the server limitation.
