### ISSUE TITLE
Call "deleteAPI" returns not implemented

### ISSUE THREAD

**Issue by frakes-zou** [influxdata/influxdb-client-go#212]
__Steps to reproduce:__
1. client = influxdb2.NewClient(Url, Token)
2. deleteAPI := client.DeleteAPI()
3. err := deleteAPI.Delete(context.Background(),org,bucket,time.Now(),time.Now(),"")

__Expected behavior:__
delete success!!!

__Actual behavior:__
When call "deleteAPI", returns 501 and Not implemented
__Specifications:__
 - Client Version: 2.0
 - InfluxDB Version: 2.0
 - Platform: golang

**Comment by bednar** [comment]
Hi @frakes-zou,

The `delete` API works only for the Influx Cloud instance.

![image](https://user-images.githubusercontent.com/455137/99788726-d147f080-2b21-11eb-9b78-f9221a6ba05a.png)

- see details: https://docs.influxdata.com/influxdb/v2.0/reference/syntax/delete-predicate/

Related issue: influxdata/influxdb#19635

Regards

**Comment by frakes-zou** [comment]
> Hi @frakes-zou,
> 
> The `delete` API works only for the Influx Cloud instance.
> 
> ![image](https://user-images.githubusercontent.com/455137/99788726-d147f080-2b21-11eb-9b78-f9221a6ba05a.png)
> 
> * see details: https://docs.influxdata.com/influxdb/v2.0/reference/syntax/delete-predicate/
> 
> Related issue: [influxdata/influxdb#19635](https://github.com/influxdata/influxdb/issues/19635)
> 
> Regards

ok，thinks!

**Comment by frakes-zou** [comment]
> Hi @frakes-zou,
> 
> The `delete` API works only for the Influx Cloud instance.
> 
> ![image](https://user-images.githubusercontent.com/455137/99788726-d147f080-2b21-11eb-9b78-f9221a6ba05a.png)
> 
> * see details: https://docs.influxdata.com/influxdb/v2.0/reference/syntax/delete-predicate/
> 
> Related issue: [influxdata/influxdb#19635](https://github.com/influxdata/influxdb/issues/19635)
> 
> Regards

ok,thanks!
