### ISSUE TITLE
Expose a method to create a service with compatibility endpoints

### ISSUE THREAD

**Issue by Jleagle** [influxdata/influxdb-client-go#213]
Hi, I am using Influx 1 and my queries fail because I am using InfluxQL instead of Flux.

I believe I need to use `/query` and `/write` endpoints but when `http.NewService()` gets called, it always adds `/api/v2/` into the endpoint paths. I can not see a way to override/skip this.

If the above is correct, it would be useful to expose methods that simply don't add `/api/v2/` into the URL. Thanks.

**Comment by vlastahajek** [comment]
@Jleagle, thanks for using this client.
This client is primarily intended for using InfluxDB 2. InfluxDB 1.8+ support is using [V2 compatibility API](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility).

For using original `write/` and `/query` endpoints, please, use the [official InfluxDB 1 client](https://github.com/influxdata/influxdb1-client).

**Comment by Jleagle** [comment]
Got it 👍
