### ISSUE TITLE
influxdb 2.0 ready for queries and writes but unauthorized access

### ISSUE THREAD

**Issue by donnol** [influxdata/influxdb-client-go#215]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

```go

func TestInflux(t *testing.T) {
	ctx := context.Background()

       client = influxdb2.NewClient("http://localhost:8086", "my-token")

	hc, err := client.Health(ctx)
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("hc: %+v\n", hc)
	if hc != nil {
		t.Logf("%v\n", *hc.Message) // ready for queries and writes
	}

	orgName := "my-org"
	bucketName := "my-bucket"

	// Use blocking write client for writes to desired bucket
	writeAPI := client.WriteAPIBlocking(orgName, bucketName)
	// Create point using full params constructor
	p := influxdb2.NewPoint("stat",
		map[string]string{"unit": "temperature"},
		map[string]interface{}{"avg": 24.5, "max": 45.0},
		time.Now())
	// write point immediately
	if err := writeAPI.WritePoint(ctx, p); err != nil {
		t.Fatal(err)
	}

	// Create point using fluent style
	p = influxdb2.NewPointWithMeasurement("stat").
		AddTag("unit", "temperature").
		AddField("avg", 23.2).
		AddField("max", 45.0).
		SetTime(time.Now())
	if err := writeAPI.WritePoint(ctx, p); err != nil {
		t.Fatal(err)
	}

	// Or write directly line protocol
	line := fmt.Sprintf("stat,unit=temperature avg=%f,max=%f", 23.5, 45.0)
	if err := writeAPI.WriteRecord(ctx, line); err != nil {
		t.Fatal(err)
	}

	// Get query client
	queryAPI := client.QueryAPI(orgName)
	// Get parser flux query result
	result, err := queryAPI.Query(ctx, `from(bucket:"`+bucketName+`")|> range(start: -1h) |> filter(fn: (r) => r._measurement == "stat")`)
	if err == nil {
		// Use Next() to iterate over query result lines
		for result.Next() {
			// Observe when there is new grouping key producing new table
			if result.TableChanged() {
				fmt.Printf("table: %s\n", result.TableMetadata().String())
			}
			// read result
			fmt.Printf("row: %s\n", result.Record().String())
		}
		if result.Err() != nil {
			fmt.Printf("Query error: %s\n", result.Err().Error())
		}
	}

	// Ensures background processes finishes
	client.Close()
}

```

__Expected behavior:__
successfully write.

__Actual behavior:__
unauthorized: unauthorized access

__Specifications:__
 - Client Version: v2.2.0
 - InfluxDB Version:2.0.2
 - Platform:ubuntu20.04

**Comment by vlastahajek** [comment]
@donnol, Is the token `my-token` really your generated authorization token?

**Comment by donnol** [comment]
I land on the "localhost:8080" web page, set the username and password, and then I use that as token like "username:password" , is that right?

**Comment by donnol** [comment]
![influxdb](https://user-images.githubusercontent.com/5707519/101716647-b17c6a80-3ad8-11eb-82c6-3e9788aaf7ab.png)

This is the login page after I set the username and password.

**Comment by donnol** [comment]
I found the token on localhost:8080 's load-data/tokens，and it work now.

Thanks.

**Comment by yogihardi** [comment]
hi @vlastahajek ,

is there any ways to generate the token from this lib instead of get from influxDB UI?

**Comment by vlastahajek** [comment]
@yogihardi, yes, use [AuthorizationsAPI](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#AuthorizationsAPI) for this.

**Comment by yogihardi** [comment]
> @yogihardi, yes, use [AuthorizationsAPI](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#AuthorizationsAPI) for this.

thank you for your reply.
with `AuthorizationsAPI` I got unauthorized access, but i figured it out with `usersAPI.SignIn(ctx, "user", "my-password")`
