### ISSUE TITLE
GetAuthorization returns panic

### ISSUE THREAD

**Issue by frbimo** [influxdata/influxdb-client-go#216]
Perhaps this is not bug but a question
I want to check validity of given username and password since `Health` and `Ready` are not cover it. 

__Steps to reproduce:__
Using `GetAuthorizations` as below :

```
...
	cli := client.NewClient(url, fmt.Sprintf("%s:%s", username, password))

	ctx, cancel := context.WithTimeout(context.TODO(), 10*time.Second)
	defer cancel()

	auth := cli.AuthorizationsAPI()
	_, err := auth.GetAuthorizations(ctx)
	if err != nil {
		return false, err
	}
```

it returns:
```
--- FAIL: TestInfluxDB (0.00s)
    --- FAIL: TestInfluxDB/test_connection_influxdb (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x90b27d]

goroutine 58 [running]:
testing.tRunner.func1.1(0x14efe00, 0x21ff680)
	/usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000321c80)
	/usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0x14efe00, 0x21ff680)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/influxdata/influxdb-client-go/v2/api.(*authorizationsAPI).listAuthorizations(0xc000010fa0, 0x1881f20, 0xc00038daa0, 0xc000536000, 0xc000508450, 0xc0001976a8, 0x175aca0)
	/home/bee/Code/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api/authorizations.go:82 +0x15d
github.com/influxdata/influxdb-client-go/v2/api.(*authorizationsAPI).GetAuthorizations(0xc000010fa0, 0x1881f20, 0xc00038daa0, 0x1881f20, 0xc00038daa0, 0xc0005084a0)
	/home/bee/Code/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api/authorizations.go:51 +0x59
gitlab.wise-paas.com/WISE-PaaS-4.0-Ops/dbservice/internal/servers.(*InfluxDB).Ready(0xc00006d740, 0x0, 0x0, 0x0)
	/home/bee/Code/go/src/gitlab.wise-paas.com/WISE-PaaS-4.0-Ops/dbservice/internal/servers/influxdb.go:43 +0x1cf
gitlab.wise-paas.com/WISE-PaaS-4.0-Ops/dbservice/internal/servers.TestInfluxDB.func1(0xc000321c80)
	/home/bee/Code/go/src/gitlab.wise-paas.com/WISE-PaaS-4.0-Ops/dbservice/internal/servers/influxdb_test.go:22 +0xc5
testing.tRunner(0xc000321c80, 0x1758ce8)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
FAIL	gitlab.wise-paas.com/WISE-PaaS-4.0-Ops/dbservice/internal/servers	0.014s
FAIL`
```

__Expected behavior:__
return `domain.Authorization` or `error`
__Actual behavior:__
panic (shown above)

__Specifications:__
 - Client Version: v2.2.0
 - InfluxDB Version: 1.8.3
 - Platform: k8s

PS: If its related to compatibility between version, any way to do check function similar like above?

**Comment by sranka** [comment]
Thank you for creating an issue, it is a defect. 

The Authorizations API is not available in InfluxDB 1.x, it is available since InfluxDB 2.x . You can check the validity of v1 credentials using an authenticated `SHOW DATABASE` query against /query v1 API. You cannot use this client library to do this because it works only with v2 API. You can either
  * execute the query using  [influxdb1-go ](https://github.com/influxdata/influxdb1-client)
  * or check 200 status code of HTTP response from a code equivalent to `curl -u username:password http://influxdb1:8086/query?q=SHOW%20DATABASES`

**Comment by frbimo** [comment]
@sranka thank you for your response, one more question, is the 2nd way (check with curl) works for both influxdb version?

**Comment by sranka** [comment]
v1 credentials can be used against v1 API in InfluxDBv2. The v2 API in InfluxDB v2 requires Token authentication, so the code `cli := client.NewClient(url, fmt.Sprintf("%s:%s", username, password))` will not work with v2, the second argument must be a real token.

**Comment by vlastahajek** [comment]
@frbimo,
you can still check the crendentials validity using this client, if you want:

 ```go
func main() {
	// Create a client
	// Supply a string in the form: "username:password" as a token. Set empty value for an unauthenticated server
	client := influxdb2.NewClient("http://localhost:8087", fmt.Sprintf("%s:%s", username, password))

	check, err := client.Health(context.Background())
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(*check.Version)

	result, err := client.QueryAPI("").QueryRaw(context.Background(), `buckets()`, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(result)
	// Close client
	client.Close()
}
```
Note, `Health()` can be used to check InfluxDB version, but works only for standalone server, not cloud.

**Comment by frbimo** [comment]
@vlastahajek this works fine. Thank you for giving the example.

**Comment by vlastahajek** [comment]
Re-opening, as when connecting to InfluxDB v1 and trying to call v2 APIs panics, which needs to be fixed.
