### ISSUE TITLE
Add a database retention policy mapping?

### ISSUE THREAD

**Issue by ryo0ka** [influxdata/influxdb-client-go#224]
__Proposal:__
Compatibility with https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostDBRP

__Current behavior:__
I can't find one if I'm not mistaken; kindly navigate me otherwise!

__Desired behavior:__
An API object should exist to provide DBRP-related functions as listed in the API docs of InfluxDB v2.0.

__Alternatives considered:__
I will make my own binding for now. Is it the standard to start with `influxdb2.Client.HTTPService()` or any recommended ways?

__Use case:__
I'm in the process of automating InfluxDB integration to our server health monitoring solution. We make heavy use of InfluxQL endpoint which requires DBRP mapping for the compatibility from v1.x as described in https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/dbrp/ 

"Not using InfluxQL" is not an option currently because InfluxQL is far more effective than Flux in a couple of aspects in our use (and in our limited knowledge as to the configs). We're bound to DBRP mapping in order to deliver the integration in our clients' favor.

**Comment by vlastahajek** [comment]
@ryo0ka, adding client API for DBRP is not currently planned, neither querying with InfluxQL.
As you pointed, you can use the generated code with the client `http.Service`.  Check  [the example of how to use generated code](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2#example-Client-CustomServerAPICall).

**Comment by ryo0ka** [comment]
@vlastahajek thanks for the heads up, closing this request
