### ISSUE TITLE
How to query with millisecond precision？

### ISSUE THREAD

**Issue by LieLieLiekey** [influxdata/influxdb-client-go#225]
I created a query, the time format is RFC3339Nano in golang time package,  but influx-UI reported an error. 
error: `compilation failed: error at @2:4-2:96: expected comma in property list, got COLON`

my query like below:
```flux
 from(bucket:"hot_profile_bucket")
|> range(start: 2006-01-02T15:04:05.999999999Z07:00, stop: 2006-01-02T15:04:05.999999999Z07:00)
|> filter(fn: (r)=> r._measurement == "stack_info"and
r.appname == "app1" and
r.hostname == "host1" and
r.pid== "100" and
r.tid == "200")
  |> duplicate(column: "_value", as: "stack")
  |> group(columns: ["stack"])
  |> count()
```

I know how to use queries with precision in seconds, but I need precision at least millisecond，Is there a way to do this?

My English is not good, please point out if there are some mistakes, thanks again !

**Comment by vlastahajek** [comment]
@LieLieLiekey, your timestamp is in the wrong format. If you are specifying a timezone offset, you cannot use the UTC marker `Z`. Either remove the timezone offset after `Z` or use offset symbols `+/-` instead of `Z`.

**Comment by LieLieLiekey** [comment]
@vlastahajek , Thank you!  my problem was solved, and I learned that influxdb queries only support these[ three time formats](https://docs.influxdata.com/influxdb/cloud/reference/flux/language/types/#timestamp-format). thanks again!
