### ISSUE TITLE
Does not retry on connection reset

### ISSUE THREAD

**Issue by elgohr** [influxdata/influxdb-client-go#226]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Don't start the influx server, so the connection for writing data is refused
2. Configure the Client to use retries
3. Try to write data
4. Turn on the influx server before the retry period is exceeded
5. See whether the data that should be written somewhen during retries is written

__Expected behavior:__
The data is written to the server, if the server is available within the retry period

__Actual behavior:__
The client stops retrying after the first connection reset

__Specifications:__
 - Client Version: v2.2.0
 - InfluxDB Version: 1.8.3
 - Platform: linux - arm

**Comment by vlastahajek** [comment]
@elgohr, thanks for the issue. This type of error was initially left out of scope for retrying, but it will be added.
