### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by vutting4221** [influxdata/influxdb-client-go#228]
__Proposal:__
Short summary of the feature.

__Current behavior:__
Describe what currently happens.

__Desired behavior:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Why is this important (helps with prioritizing requests)?

**Comment by vlastahajek** [comment]
@vutting4221, it seems like an issue by mistake, isn't it?
