### ISSUE TITLE
"Ready" not available in 1.8.x

### ISSUE THREAD

**Issue by jkandasa** [influxdata/influxdb-client-go#238]
Recently replaced `Ping` with `Ready`.
But still, this client library supports 1.18.x, in 1.8.x the `ready` API is not available.

__Steps to reproduce:__
1. setup 1.8.x influxd
2. Connect and call `Ready` func
3. Failing with `404` error

__Expected behavior:__
Should work in 1.8.x

__Actual behavior:__
`Ready` throws `404`, error in 1.8.x

__Specifications:__
 - Client Version: v2.2.2 (github.com/influxdata/influxdb-client-go/v2)
 - InfluxDB Version: 1.8.5rc0-1
 - Platform: arm/v7

**Comment by vlastahajek** [comment]
@jkandasa, InfluxDB 1.8 doesn't support the `/ready` endpoint. The [only compatible 1.8 endpints](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility) are `/health/`, `/api/v2/write` and `/api/v2/query`. 
You can use [Client.Health()](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2#Client.Health) to check the server status.

**Comment by jkandasa** [comment]
@vlastahajek Thanks, it helps!
