### ISSUE TITLE
Coverage report only includes e2e tests and only `api` and `internal` (sub)packages

### ISSUE THREAD

**Issue by aldas** [influxdata/influxdb-client-go#245]
Currently coverage is reported only for  `api` and `internal` (sub)packages and only for e2e tests

> -coverpkg '.,./api/...,./internal/...'

https://github.com/influxdata/influxdb-client-go/blob/fa15edd8bd9549750d2f93b6ccb386434df63fbe/.circleci/config.yml#L49

NB: unit tests are extremely slow (mostly due using long retry intervals)

```bash
x@x:~/code/influxdb-client-go$ time GOFLAGS="-count=1" go test ./...
ok      github.com/influxdata/influxdb-client-go/v2     3.518s
ok      github.com/influxdata/influxdb-client-go/v2/api 8.127s
ok      github.com/influxdata/influxdb-client-go/v2/api/http    0.008s
ok      github.com/influxdata/influxdb-client-go/v2/api/query   0.013s
ok      github.com/influxdata/influxdb-client-go/v2/api/write   0.064s
?       github.com/influxdata/influxdb-client-go/v2/domain      [no test files]
?       github.com/influxdata/influxdb-client-go/v2/internal/examples   [no test files]
ok      github.com/influxdata/influxdb-client-go/v2/internal/gzip       0.023s
?       github.com/influxdata/influxdb-client-go/v2/internal/http       [no test files]
ok      github.com/influxdata/influxdb-client-go/v2/internal/log        0.027s
?       github.com/influxdata/influxdb-client-go/v2/internal/test       [no test files]
ok      github.com/influxdata/influxdb-client-go/v2/internal/write      31.167s
ok      github.com/influxdata/influxdb-client-go/v2/log 0.005s
ok      github.com/influxdata/influxdb-client-go/v2/main        0.002s [no tests to run]

real    0m31.928s
user    0m3.657s
sys     0m0.707s
```

**Comment by vlastahajek** [comment]
> Currently coverage is reported only for api and internal (sub)packages and only for e2e tests

Why do you think so?

NB: Let skip philosophical discussion whether to call such tests  `unit tests`. 
Some of them are long cause functionality requires such testing. I could skip such tests in the `short` mode, but as this mode is not used in CI, they not marked yet..

**Comment by aldas** [comment]
> Why do you think so?

this is what I see from Codecov report. There is no `log` and `domain` packages reported.  `log` has unit tests and `domain` has functions for API endpoints (which may and/or may not be covered)

![codecov](https://user-images.githubusercontent.com/2320301/114669721-ddb82a00-9d0a-11eb-95fa-1db8f2637291.png)


> Some of them are long cause functionality requires such testing

retry interval is configurable. `TestCustomRetryDelayWithFLush` already tests same stuff with reasonable speed. `TestDefaultRetryDelay` with ~30s execution time adds almost no value and make waiting for unit tests to complete unreasonably long.

**Comment by vlastahajek** [comment]
Ok, good point, the `log` package was forgotten to include in the coverage report, when it was added. 

The `domain` package is out scoped intentionally. It contains types and client stub generated from swagger. Many of those are not used and cannot be filtered easily. It is in negotiation how to mark desired operations in the server swagger usable in clients.
The used part is tested in e2e tests. 
As the code generated, it is considered trustworthy.

However, generally, "unit tests" are part of the coverage report, also the root folder.
