### ISSUE TITLE
Influx2.0Version. How to find data count?

### ISSUE THREAD

**Issue by water-gulugulu** [influxdata/influxdb-client-go#247]
Golang No use method was found

**Comment by vlastahajek** [comment]
@water-gulugulu, I'm not sure what do you need exactly.

If you need to know the count of data in advance, you can first query data with [Flux count()](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/aggregates/count/) function.

In the case of totally processed data, you can count rows as you iterate over query results. In this case, you can aggregate count based on your needs, cause Flux query results can have multiple tables.

**Comment by vlastahajek** [comment]
Closing as there is no response.
