### ISSUE TITLE
Cannot use method SetHTTPClient: type *influxdb2.Options has no field or method SetHTTPClient

### ISSUE THREAD

**Issue by wkomor** [influxdata/influxdb-client-go#257]
I try to use custom HTTP client as described in the README by following

```
func ConnectInflux(config *settings.Settings) {
	opt := influxdb2.DefaultOptions()
	opt.SetPrecision(time.Millisecond)
	opt.SetBatchSize(uint(config.InfluxBatchSize))
	opt.SetUseGZip(true)
	httpClient := &http.Client{
		Timeout: time.Second * time.Duration(60),
		Transport: &http.Transport{
			DialContext: (&net.Dialer{
				Timeout: 5 * time.Second,
			}).DialContext,
			TLSHandshakeTimeout: 5 * time.Second,
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
			MaxIdleConns:        100,
			MaxIdleConnsPerHost: 100,
			IdleConnTimeout:     90 * time.Second,
		},
	}
	opt.SetHTTPClient(httpClient)
	cl := influxdb2.NewClientWithOptions(
		config.InfluxHost,
		config.InfluxToken,
		opt,
	)
	WriteAPI = cl.WriteAPI("my_org", config.InfluxDB+"/autogen")
}
```

and then I got build error type *influxdb2.Options has no field or method SetHTTPClient

__Expected behavior:__
Build successful

__Actual behavior:__
opt.SetHTTPClient undefined (type *influxdb2.Options has no field or method SetHTTPClient)

__Specifications:__
 - Client Version: 2.3.0
 - InfluxDB Version: 1.8.0
 - Platform: Linux

**Comment by vlastahajek** [comment]
For sure [the method is there](https://github.com/influxdata/influxdb-client-go/blob/master/options.go#L149) and your code works OK (just missing `:=` in the WriteAPI assignment)

Do you have import: `"github.com/influxdata/influxdb-client-go/v2"`?

**Comment by wkomor** [comment]
Sorry, this is my fault. 
I just recognized that my imports looks like 

```influxdb2 "github.com/influxdata/influxdb-client-go" ```

not .../v2.

 With "github.com/influxdata/influxdb-client-go/v2" everything works fine. Thanks a lot for help. Issue might be closed.
