### ISSUE TITLE
Go get can't find github.com/influxdata/influxdb-client-go/v2

### ISSUE THREAD

**Issue by bertrand1974** [influxdata/influxdb-client-go#260]
__Steps to reproduce:__
`go get github.com/influxdata/influxdb-client-go/v2` doesn't find the package.

__Expected behavior:__
I would expect the `go get` command to install the influxdb2 go client.

__Actual behavior:__
Instead, I get this error message:
`go get github.com/influxdata/influxdb-client-go/v2
cannot find package "github.com/influxdata/influxdb-client-go/v2" in any of:
        /usr/lib/golang/src/github.com/influxdata/influxdb-client-go/v2 (from $GOROOT)
        /home/bertrand/go/src/github.com/influxdata/influxdb-client-go/v2 (from $GOPATH)
`
but if I do `go get github.com/influxdata/influxdb-client-go`, it doesn't give me an error message.

__Specifications:__
 - Platform: Fedora 33
 - Golang: 1.15.12

**Comment by vlastahajek** [comment]
@bertrand1974 , you need `go.mod` in the project to use this command. To start with `go.mod` just run: `go mod init package-name`, and replace `package-name` with your package name.
If you don't want to use `go.mod`, `GOPATH` based project, just use `go get githtub.com/influxdata/influxdb-client-go`.
