### ISSUE TITLE
Deprecate github.com/pkg/errors

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb-client-go#262]
Influx client still uses github.com/pkg/errors, only occurrences I could find being in https://github.com/influxdata/influxdb-client-go/tree/master/domain. With go 1.13 as minimum version it should be possible to use the newer Go mechanisms of `errors.Is/As` instead.

**Comment by vlastahajek** [comment]
@andig, as you noted, the `github.com/pkg/errors` is used in the generated code. This will need to be fixed in the [oapi-generator](https://github.com/deepmap/oapi-codegen/pulls/vlastahajek).

**Comment by andig** [comment]
Thanks, didn't realize where this was coming from.
