### ISSUE TITLE
Query with Select

### ISSUE THREAD

**Issue by Eghbalii** [influxdata/influxdb-client-go#263]
I need to find out the time of last data saved in just a specific measurement(without any important tag or field option). Find [this link ](https://stackoverflow.com/questions/41377415/query-the-most-recent-timestamp-max-last-for-a-specific-key-in-influx) useful . But have no idea how to query with `SELECT` !
 I try this below code with Query and QueryRaw.
`query := fmt.Sprintf("SELECT * FROM %s [WHERE Market=%s] ORDER BY time DESC LIMIT 1", measurement, market)
 queryAPI := client.QueryAPI(org)
 result, err := queryAPI.Query(context.Background(), query)`
and get this unclear error : 
invalid: compilation failed: error at @1:38-1:45: invalid expression @1:37-1:38: =

__Specifications:__
 - Client Version: 2
 - InfluxDB Version: 2 
 - Platform: Ubuntu

**Comment by vlastahajek** [comment]
@Eghbalii, this client doesn't support InfluxQL, only [Flux](https://docs.influxdata.com/influxdb/v2.0/query-data/get-started/). You can either use [InluxDB 1 client](https://github.com/influxdata/influxdb1-client), or write query using Flux, eg:
```
from(bucket:"your-database")
  |> range(start:-1h)
  |> filter(fn:(r) =>
    r._measurement == "%s" and
    r.market == "%s"
  )
  |> last()
```
Flux query requires a time range, so make sure you specify the correct range.
You can test the query in Chronograf or in the DataExplorer of InfluxDB 2 UI, in case you use InfluxDB 2.

**Comment by Eghbalii** [comment]
Thanks for your quickly answering . That work nicely , but the problem is: in my program maybe the time range not clear for a while . So whats the biggest range? for example is that support a year? or any better suggestion?

**Comment by vlastahajek** [comment]
The range depends on your data and the server. A long-range means a lot of data to process. You can specify whatever time range you need (e.g. relative two years back: `start: -2y`). You can easily test how it performs by trying such queries.
Read more [about time range here](https://docs.influxdata.com/influxdb/v2.0/query-data/get-started/query-influxdb/#2-specify-a-time-range). 
You can also iteratively test ranges in smaller intervals until you find data.

**Comment by bednar** [comment]
Hi @hooklab,

If you're looking to paginate your query results, you can make use of the `limit` function available in Flux. This function allows you to specify the number of records you want to retrieve from your dataset, which can be very useful for implementing pagination.

For more detailed information on how to use the `limit` function, please refer to the official Flux documentation here: [Flux limit function documentation](https://docs.influxdata.com/flux/v0/stdlib/universe/limit/).

If you need further assistance or have any other questions, feel free to reach out.

Best regards
