### ISSUE TITLE
Race condition on logger struct with multiple concurrent clients

### ISSUE THREAD

**Issue by mateuszkowalke** [influxdata/influxdb-client-go#268]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run multiple clients concurrently with race detection.

__Expected behavior:__
No race conditions.

__Actual behavior:__
Race detected on writes to logger struct when setting log level.

__Specifications:__
 - Client Version: v2
 - InfluxDB Version: v2.0.5
 - Platform: ubuntu 20.04

**Comment by shubhamcoc** [comment]
Sorry to comment on a closed ticket, but the race condition occurs if we try to create 2 clients. 

Below is the trace log 

==================
WARNING: DATA RACE
Write at 0x000001c8c870 by goroutine 53:
  github.com/influxdata/influxdb-client-go/v2/log.(*logger).SetLogLevel()
      /home/shubham/go/src/gerrit.ext.net.nokia.com/gerrit/AANM/omes-opentsdb-uploader/vendor/github.com/influxdata/influxdb-client-go/v2/log/logger.go:62 +0x76
  github.com/influxdata/influxdb-client-go/v2.NewClientWithOptions()
      /home/shubham/go/src/gerrit.ext.net.nokia.com/gerrit/AANM/omes-opentsdb-uploader/vendor/github.com/influxdata/influxdb-client-go/v2/client.go:122 +0x56f
  gerrit.ext.net.nokia.com/AANM/service/omes-opentsdb-uploader/pkg/influxdb/client.(*influxClient).Init()
      /home/shubham/go/src/gerrit.ext.net.nokia.com/gerrit/AANM/omes-opentsdb-uploader/pkg/influxdb/client/influxClient.go:45 +0x126
  gerrit.ext.net.nokia.com/AANM/service/omes-opentsdb-uploader/pkg/dbInterface.(*dbInterface).InitDB()
      /home/shubham/go/src/gerrit.ext.net.nokia.com/gerrit/AANM/omes-opentsdb-uploader/pkg/dbInterface/dbInterface.go:81 +0xcba
  gerrit.ext.net.nokia.com/AANM/service/omes-opentsdb-uploader/pkg/server.Start()
      /home/shubham/go/src/gerrit.ext.net.nokia.com/gerrit/AANM/omes-opentsdb-uploader/pkg/server/server.go:140 +0x3e9

 

Previous read at 0x000001c8c870 by goroutine 84:
  github.com/influxdata/influxdb-client-go/v2/log.(*logger).Info()
      /home/shubham/go/src/gerrit.ext.net.nokia.com/gerrit/AANM/omes-opentsdb-uploader/vendor/github.com/influxdata/influxdb-client-go/v2/log/logger.go:100 +0x5a
  github.com/influxdata/influxdb-client-go/v2/internal/log.Info()
      /home/shubham/go/src/gerrit.ext.net.nokia.com/gerrit/AANM/omes-opentsdb-uploader/vendor/github.com/influxdata/influxdb-client-go/v2/internal/log/logger.go:36 +0xc4
  github.com/influxdata/influxdb-client-go/v2/api.(*WriteAPIImpl).bufferProc()
      /home/shubham/go/src/gerrit.ext.net.nokia.com/gerrit/AANM/omes-opentsdb-uploader/vendor/github.com/influxdata/influxdb-client-go/v2/api/write.go:136 +0x75
==================

**Comment by mateuszkowalke** [comment]
This issue should've been resolved in release 2.5.0. Could you please make sure you are using it?

**Comment by shubhamcoc** [comment]
In my go.mod file, it is github.com/influxdata/influxdb-client-go/v2 v2.5.0
