### ISSUE TITLE
How to generate a query url with "api/v1/query?org=" instead of "api/v2query?org="

### ISSUE THREAD

**Issue by kaiyuliusp** [influxdata/influxdb-client-go#282]
<!--
    It generates "http://localhost:8428/api/v2/query_range" with function QueryAPI(), which get a response "remoteAddr: "172.19.0.1:63772"; requestURI: /api/v2/query_range; unsupported path requested: "/api/v2/query_range"".
    I have test the "*/api/v1/query?org=" ok. So i wonder how to generate "api/v1" with function QueryAPI().

**Comment by kaiyuliusp** [comment]
Function QueryAPI generate url "http://localhost:8428/api/v2/query_range" and get the response "remoteAddr: "172.19.0.1:63772"; requestURI: /api/v2/query_range; unsupported path requested: "/api/v2/query_range"".
I have test "*/api/v1/query_range" which works well. So i wonder how to generate "*/api/v1/query_range" with function QueryAPI().  thx.

**Comment by vlastahajek** [comment]
@kaiyuliusp, neither `/api/v2/query_range` or `/api/v1/query_range` are part of **InfluxDB 2 Server** API.
It looks like you are trying to connect to **Prometheus**

**Comment by kaiyuliusp** [comment]
> Prometheus

ohhh sry, i am new to influxdb. i use docker to install the influxdb, so do you know how to query it by influxdata.

**Comment by vlastahajek** [comment]
InfluxDB is usually available on port 8086. Your original issue seems to be you are using a Prometheus client, not this one. Make sure you are using this library (`github.com/influxdata/influxdb-client-go/v2`)

**Comment by vlastahajek** [comment]
Check [Readme](https://github.com/influxdata/influxdb-client-go#queries) for examples of querying data.
