### ISSUE TITLE
Query API does not expose table's name

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb-client-go#283]
I have a Flux query that yields two distinct tables:

```
import "generate"

generate.from(count: 1, fn: (n) => 0, start: now(), stop: now())
  |> yield(name: "foo")

generate.from(count: 1, fn: (n) => 1, start: now(), stop: now())
  |> yield(name: "bar")
```

The resulting CSV is formatted like this:

```csv
#group,false,false,false,false
#datatype,string,long,dateTime:RFC3339,long
#default,foo,,,
,result,table,_time,_value
,,0,2021-11-09T20:50:58.440510582Z,0

#group,false,false,false,false
#datatype,string,long,dateTime:RFC3339,long
#default,bar,,,
,result,table,_time,_value
,,0,2021-11-09T20:50:58.440510582Z,1
```

The raw data view in the UI understands the table names:

![Screen Shot 2021-11-09 at 3 52 59 PM](https://user-images.githubusercontent.com/290647/141002865-846e0395-39f2-41a9-98ac-83f86a03b278.png)

However, the Go client only exposes the table numbers: https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.5.1/api/query#FluxTableMetadata

AFAICS there is no way to access the table name, which prevents me from easily consuming queries with yield. To the best of my knowledge, with real queries that take time to execute, the table ID is unpredictable and cannot be used to determine which table is which.

**Comment by sranka** [comment]
Just FYI: the default value of the `result` column is the thing that you are looking for. The go client should better propagate the default value into FluxRecord values.

**Comment by vlastahajek** [comment]
@mark-rushakoff, as @sranka suggests, read value if the `result` column to get what you need:
```go
tableName := queryResult.Record().ValueByKey("result")
```

**Comment by mark-rushakoff** [comment]
Thanks, `ValueByKey("result") worked for my use case. I'll defer to you all on whether there is any further action for this issue.

**Comment by vlastahajek** [comment]
PR #287 adds `Result()` function as a quick accessor for this column value.
