### ISSUE TITLE
proposal: Make buffered writer one time use

### ISSUE THREAD

**Issue by GeorgeMac** [influxdata/influxdb-client-go#29]
As per suggestion in https://github.com/influxdata/influxdb-client-go/pull/28

The semantics of Start and Stop are a little tricky. Ideally Start and Stop need to be synchronized and flip/flop between being able to be called. The current implementation raises a number of race and deadlock hazards and is a good example of how tricky it is to implement.

That said I see little value in having Start and Stop semantics. Personally I would like to start a periodic flushing buffer and eventually close it. If I need another, I would just create a new instance. Without a solid use-case for Start and Stop I would suggest that we remove it in favor of something like:

```go
type LPWriter struct {}

func (*LPWriter) Start() {
//...
}

func (*LPWriter) Flush() {
//...
}

func (*LPWriter) Close() error { return nil }
```

A further suggestion would be that we remove periodic flushing altogether. In favor of just a Flush method. Then we write a type which takes a `type WriteFlusher interface {}` and moves periodic flushing respoinsibility elsewhere.

Thoughts?

**Comment by docmerlin** [comment]
I like the idea.  I think it simplifies the interface into the LPWriter.

**Comment by GeorgeMac** [comment]
Delivered in #28
