### ISSUE TITLE
Add WriteBatch to WriteAPIBlocking

### ISSUE THREAD

**Issue by pabigot** [influxdata/influxdb-client-go#295]
__Proposal:__
Extend the blocking API to allow writing a batch of already-aggregated line protocol records.

__Current behavior:__
The blocking API only accepts individual points, or points already converted to records.  The implemented functions then go on to do the conversion and aggregation to create a batch.

__Desired behavior:__
To write a batch that I've created myself.

__Use case:__
I'm continuing my attempt to use this package in a context where I can't tolerate lost data due to the server being inaccessible.

The non-blocking API has a variety of problems raised in other issues, but the showstopper is that it will drop data without allowing the application to recover the data; e.g. in [this path](https://github.com/influxdata/influxdb-client-go/blob/4218b5069e003d9575d6d8221a43f7eed6e5f6ec/internal/write/service.go#L142) but also in a [shutdown situation](https://github.com/influxdata/influxdb-client-go/pull/291#issuecomment-993673829).

The documentation of [WriteAPIBlocking](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.6.0/api#WriteAPIBlocking) notes that it should be used when:

> there is a need to have explicit control of failed batches.

The problem in my situation is that `WriteAPIBlocking` accepts only on individual points or line-protocol records (possibly in a slice, but still separated).  In my application, if I need to persist unwritten points the natural encoding is newline-separated (or terminated) line protocol records in a byte sequence.  However, when I read that back off disk and prepare to resend it the current API requires me to split it into individual records at the newline, so that WriteRecord can then add the newlines back and aggregate it again.

This is cumbersome, but trivially avoided by extending the API to allow writing a batch.

**Comment by vlastahajek** [comment]
The already existing `WriteRecord` function can also take just a single string. And such string can be a batch.
