### ISSUE TITLE
WriteAPI and QueryAPI are not found

### ISSUE THREAD

**Issue by davidhuawei** [influxdata/influxdb-client-go#303]
Hi,
I'm running the client for influxdb:1.8.6-alpine docker image, and couldn't run successfully even the sample code from the documentation:
https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility

the error that I get when I tried to execute writeApi.WritePoint(...):
Code: 404 Not Found
Message: database not found: "test"

the client.Health(...) request works good and returns Message "ready for queries and writes" with Status "pass" and db compatible version.

**Comment by sranka** [comment]
> Message: database not found: "test"

Your influxdb does not have a database named `test`, you need to setup an existing database or create a new one. 2.x API uses buckets in form of 1.x `database/retentionPolicy`, the fully qualified bucket name is `test/autogen`.

**Comment by davidhuawei** [comment]
> > Message: database not found: "test"
> 
> Your influxdb does not have a database named `test`, you have to use an existing database or create a new one named `test`. 2.x API uses buckets in form of 1.x `database/retentionPolicy`, the fully qualified bucket name is ussually `test/autogen`.

thanks for the support.
I'm migrating my code from using influxdb1-client to the current api version.

So how can I create a database using new client api ?
at the previous version I got it using the method client.QueryContext without specified dbName with the query command "create database test"

what is the client solution for creating db using influx version 1.8 ?

**Comment by vlastahajek** [comment]
This was resolved in #305.
