### ISSUE TITLE
How to create a new database using client ?

### ISSUE THREAD

**Issue by davidhuawei** [influxdata/influxdb-client-go#305]
Hi,
I'm using influxdb version 1.8.6, and migrating code from using influxdb1-client package to the current api version.

I'm Trying to create a new database using the client api. 
At the previous version of client I was doing it using the method client.QueryContext() - without specified dbName, and with the query command "create database test"

On the current client library this method is not exposed anymore, so my question is how can I create a new database ?

Thanks

**Comment by vlastahajek** [comment]
@davidhuawei, this library primarily supports InfluxDB 2. InfluxDB 1 is supported via [forward compatibility API](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility). 
InfluxQL and associated expressions are not supported. Use [influxdb1-client](https://github.com/influxdata/influxdb1-client) for that.

**Comment by davidhuawei** [comment]
> InfluxQL

When I use the flag flux-enabled=true => then I can query the db.
The only thing that I can't do is creating a database - what is the solution for create db functionality on the current version library ?

**Comment by davidhuawei** [comment]
> @davidhuawei, this library primarily supports InfluxDB 2. InfluxDB 1 is supported via [forward compatibility API](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility). InfluxQL and associated expressions are not supported. Use [influxdb1-client](https://github.com/influxdata/influxdb1-client) for that.

When I use the flag flux-enabled=true => then I can query the db.
The only thing that I can't do is creating a database - what is the solution for create db functionality on the current version library ?

**Comment by sranka** [comment]
The v2 API (and this client library)  is not capable to create a v1 database. 

You can upgrade your InfluxDB to the latest 2.x and then create a `test` bucket using BucketsAPI. If you don't want to use the v1 client anymore, you might be able to create a database with an HTTP call documented in https://docs.influxdata.com/influxdb/v1.8/tools/api/#create-a-database-using-basic-authentication.
