### ISSUE TITLE
Using `CreateTaskWithCron` with flux script containing `import "xxxx"` statement will always throw an error

### ISSUE THREAD

**Issue by AnalogJ** [influxdata/influxdb-client-go#322]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

```
taskScript := `
import "types"
from(bucket: "example-bucket")
    |> range(start: -task.every)
    |> filter(fn: (r) => r._measurement == "mem" and r.host == "myHost")
`
 xxx.influxTaskApi.CreateTaskWithCron(ctx, "mytask", taskScript, "0 1 * * 0", "myorg")
```

__Expected behavior:__
Should create the task.

When creating this simple task manually using the UI, the generated task looks like the following. 
**Note how the `import "types"` line has been hoisted above the `option task = {` block.**

```
import "types"
option task = { 
  name: "mytask",
  every: 1h,
}

from(bucket: "example-bucket")
    |> range(start: -task.every)
    |> filter(fn: (r) => r._measurement == "mem" and r.host == "myHost")
```

__Actual behavior:__
Throws an error with the following message:

```
panic: invalid: invalid options: loc 2:1-2:7: invalid statement @2:1-2:7: import
```

I think the API creation is not correctly hoisting the import statement above the `option task` block. 
See: 
https://github.com/influxdata/influxdb-client-go/blob/a842d5113a8780656bcee34a83e29c159e6faf04/api/tasks.go#L229

__Specifications:__
 - Client Version: `github.com/influxdata/influxdb-client-go/v2 v2.2.3`
 - InfluxDB Version: `2.2`
 - Platform:

**Comment by vlastahajek** [comment]
@AnalogJ, thanks for the issue. I will add `CreateTaskByFlux(ctx context.Context, flux, orgID string) (*domain.Task, error)`, where you will have full control on the task source script as it is in the UI

**Comment by AnalogJ** [comment]
That would fix it, thanks!
