### ISSUE TITLE
WriteAPI writes to database in a very slow rate  

### ISSUE THREAD

**Issue by fthdrmzzz** [influxdata/influxdb-client-go#333]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ... Run influxdb in a docker container
2. ... Using blocking WriteAPI send 250 points.
3. ... Using QueryAPI execute flux Query to get # of rows.

__Expected behavior:__
250  expected to be retrieved as # of rows.

__Actual behavior:__
Much less number is retrieved. When I query influxdb by hand on the UI, I observed that the points are saved to the database one by one at a very slow rate.

__Specifications:__
 - Client Version: 2.9.0
 - InfluxDB Version: 2.2
 

The way I write 250 points:
```go
writeAPI := repo.client.WriteAPIBlocking(repo.cfg.Org, repo.cfg.Bucket)
err = writeAPI.WritePoint(context.Background(), pts...)
return err
```

The way I query db:
```go
rowCount    = fmt.Sprintf(`from(bucket: "%s") 
|> range(start: -1h) 
|> filter(fn: (r) => r["_measurement"] == "messages")
|> filter(fn: (r) => r["_field"] == "dataValue" or r["_field"] == "stringValue" or r["_field"] == "value" or r["_field"] == "boolValue" or r["_field"] == "sum" )
|> group(columns: ["_measurement"])
|> count()
|> yield(name: "count")`, repoCfg.Bucket)


queryAPI := client.QueryAPI(repoCfg.Org)

// get QueryTableResult
result, err := queryAPI.Query(context.Background(), rowCount)
```

**Comment by vlastahajek** [comment]
All points are sent in a single call. 
It takes 28ms to write 1441 simple points (two tags, two fields) to InfluxDB 2.20 in Docker Desktop running on a laptop with Windows 10.

Did you set a timestamp for each point? If not, the server assigns a timestamp and it can be the same for several points and the last wins.

**Comment by fthdrmzzz** [comment]
I set a timestamp for each point in the code,

Here How I prepare the points
```go
for _, msg := range msgs {
	var pts []*write.Point
	for _, msg := range msgs {
		tgs, flds := senmlTags(msg), senmlFields(msg)

		sec, dec := math.Modf(msg.Time)
		t := time.Unix(int64(sec), int64(dec*(1e9)))

		pt := influxdb2.NewPoint(senmlPoints, tgs, flds, t)
		pts = append(pts, pt)
	}

	return pts, nil
```

**Comment by vlastahajek** [comment]
And the time of points are in the range of the last hour, as set in the query?

**Comment by fthdrmzzz** [comment]
Yes, I also tried different variations. I tried querying for last 6 hours and get the same result.

**Comment by vlastahajek** [comment]
OK. Does _WritePrecision_ is left set to _Nanoseconds_? 
Can you enable debug and check data that are sent?
```go
client := influxdb2.NewClientWithOptions("http://localhost:8086", "my-token", influxdb2.DefaultOptions().SetLogLevel(log.DebugLevel))
```

**Comment by fthdrmzzz** [comment]
I did not do such configuration by hand. If It is not default It is not set.
I am checking the sent data as you suggested

**Comment by fthdrmzzz** [comment]
It returns 250 rows. I checked that timestamp of rows are unique. 

I want to point this out: It gives 250 rows in the db eventually.  But It does this in a very slow rate so that my test fails. In the debug log you can see the query. 

Query log is after 250 lines of message log. However, query returns some unexpected number (11 for this run). If I wait and query again, I can see the number of messages increasing. It reaches to 250 eventually.

**Comment by vlastahajek** [comment]
As you are using the blocking write client, at the time the write call completes and the application continues with the query, the server got all data.
Can you check InfluxDB server logs, if there is any useful information?

 Where are the docker host and client? Are they on the same machine?

**Comment by vlastahajek** [comment]
Thanks. 
You may write some point in the server future time. You can check this, by adding `stop` with some future time to the query time range, e.g. `stop: 1h`.

Can you verify, that origin of data and server have time synced?

**Comment by vlastahajek** [comment]
@fthdrmzzz, anything new?

**Comment by fthdrmzzz** [comment]
Sir I will update you and continue on the issue on friday due to my availability. Please do not close this issue.

**Comment by fthdrmzzz** [comment]
`You may write some point in the server future time.`

It turns out that this is the case for the problem. I can get all 250 messages when I added stop: 1h. Thank you for your time
