### ISSUE TITLE
Improve error handling in write client

### ISSUE THREAD

**Issue by sjwang90** [influxdata/influxdb-client-go#337]
"retry X times until successful, or else error" is a common write pattern that the Go client library does not currently handle well. It would be helpful to have an example for this pattern or change the API since that example may be hard to write. 

@lesam

**Comment by lesam** [comment]
'common pattern' meaning a common thing people want for writing time series data. Often there will be some process that will have a large stream of incoming data and need to write it to InfluxDB, and retry temporary failures (e.g. the network connection was interrupted during the write).

**Comment by vlastahajek** [comment]
Go V2 client (this library) supports the same automatic back-pressure strategy as all the official v2 clients. 
This means that if there is a connection/network error or the server responds with HTTP status code >=429 the client keeps the data and retries writing with increasing retry delay until the maximum retry attempts is reached or maximum retry time runs out.
This is supported in the asynchronous `WriteAPI`. By using synchronous `BlockingWriteAPI` user has to handle errors manually.

**Comment by lesam** [comment]
Hmm - I did not know this! I'd still like for `Flush` to return the error instead of having to subscribe to the `Errors` channel separately, but that's a small point.

**Comment by lesam** [comment]
That will teach me to read the docs more closely...

**Comment by vlastahajek** [comment]
@sjwang90, @lesam, It seems the main topic of this issue was resolved by explaining how the Go client works. Is there anything unclear?

**Comment by sjwang90** [comment]
I think we're good. Feel free to re-open @lesam if not.
