### ISSUE TITLE
Flush doesn't perform retries of write failures

### ISSUE THREAD

**Issue by lesam** [influxdata/influxdb-client-go#340]
The default write retry logic is documented to retry 5 times before failing.

It seems this may not in fact be the case.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

I have created a test showing what I believe to be the broken behaviour: https://github.com/influxdata/influxdb-client-go/pull/339

__Expected behavior:__

`Flush` should wait for all retries to complete

__Actual behavior:__

It seems `Flush` does not wait for retries and the data appears to be lost.

__Specifications:__
 - Client Version: current

**Comment by vlastahajek** [comment]
@lesam, the use-case in the test is not what async WriteAPI is designed for. 
There are two problems:

1. WriteAPI is intended for the continuous data stream, where automatic batching and automatic flush is useful. Retrying is triggered by another write, not a scheduler. See other test, where other writes are performed to trigger retrying. 

Fully controlled write should done by WriteAPIBlocking. There is a simple batch wrapper example in the the [API Doc](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#WriteAPIBlocking) for adding automatic batching.

2. Flush is designed for forcing write buffer. The flush method is added for convenience, not all official clients support this.

**Comment by lesam** [comment]
I think the more intuitive solution would be for flush to flush all pending writes, including retries.

If people don't actually want retries, they could set `MaxRetries` to `0` or we could add `FlushWithoutRetry` for users that actually want this case (I assume very few of them do).

Note that the current situation is that `Flush` does not even print an error message when writes are dropped, so there is currently no way (as far as I can tell) to use the async API and be sure whether all writes were eventually successful or not, and if not, which writes were unsuccessful. At the very least, users need a way to find out which writes were unsuccessful.

**Comment by vlastahajek** [comment]
There is a possibility to set [WriteFailedCallback](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#WriteFailedCallback) which synchronously notifies the client about each write failure.

But, I understand that Error would be better for messages about dropping data. I will change this.
