### ISSUE TITLE
coroutine safe in internal/write/service.go

### ISSUE THREAD

**Issue by hubugui** [influxdata/influxdb-client-go#347]
# Specifications

Client Version: v2.9.2
InfluxDB Version:v2.3.0
Platform:Ubuntu 20.04

# [internal/write/service.go](https://github.com/influxdata/influxdb-client-go/blob/v2.9.2/internal/write/service.go)

I see Write.go have [Flush() ](https://github.com/influxdata/influxdb-client-go/blob/v2.9.2/api/write.go#L114) and [writeProc()](https://github.com/influxdata/influxdb-client-go/blob/v2.9.2/api/write.go#L185), them maybe called at the same time, and  [HandleWrite()](https://github.com/influxdata/influxdb-client-go/blob/v2.9.2/internal/write/service.go#L113) and [Flush()](https://github.com/influxdata/influxdb-client-go/blob/v2.9.2/internal/write/service.go#L265) didn't use a lock to protect retryQueue and write batch. 

excuse me, is my understanding correct?

**Comment by vlastahajek** [comment]
@hubugui, thanks for a deep look into this client. 
You are right.
The implementation is optimistic due the two assumptions:
- Flush doesn't need to be really used. WriteAPI flushes automatically when the batchsize is reached or a flush timeout occurs
- Retry queue is used rarely.

E.g. use case, when you have several concurrent go-routines writing points and finally flushing to make sure everything is written is more suitable for WriteAPIBlocking.

What is your use case?

**Comment by hubugui** [comment]
@vlastahajek 

Thank you for your explain!

My use case is use WriteAPI() and depend automatically flush in backgroud. I only found this assumptions when learned the code, so want confirm it with develop team.

I will close this issue, Thanks!
