### ISSUE TITLE
LPWriter.org is never assigned

### ISSUE THREAD

**Issue by ernestoalejo** [influxdata/influxdb-client-go#35]
When `org` is passed [here](https://github.com/influxdata/influxdb-client-go/blob/develop/writer.go#L65) it is not used inside the function. Then when writing the metrics `w.org` [is used](https://github.com/influxdata/influxdb-client-go/blob/develop/writer.go#L174), which is always empty.

**Comment by docmerlin** [comment]
Thanks @ernestoalejo
