### ISSUE TITLE
APIClient().GetChecks return null checks

### ISSUE THREAD

**Issue by drohlicek** [influxdata/influxdb-client-go#371]
### Specifications

* Client Version: v2.12.0
* InfluxDB Version: 2.4.0
* Platform: macOS

### Steps to reproduce
```go
var Params = domain.GetChecksParams{OrgID: orgID}
influxClient := influxdb2.NewClientWithOptions(url, token, influxdb2.DefaultOptions().SetUseGZip(true).SetLogLevel(2).SetApplicationName("Testing"))
check, err := influxClient.APIClient().GetChecks(context.Background(), &Params)
if err != nil {
	log.Panic("Error GetChecks")
}
fmt.Printf("%v\n", check.Checks)

code return
&[{<nil>} {<nil>}]
```

### Expected behavior

When I tested with Postman, server reply json response with 2 checks

### Actual behavior
```go
code return
&[{<nil>} {<nil>}]
```

**Comment by vlastahajek** [comment]
@drohlicek, thanks for using this client and reporting the issue. 
Unfortunately `GET` Checks response has a complex schema in the server swagger (the `allOf` construct with discriminator)  and the swagger generator produces the wrong structure.
We will try to fix this.
