### ISSUE TITLE
Allow Querying through InfluxQL

### ISSUE THREAD

**Issue by n-is** [influxdata/influxdb-client-go#373]
__Proposal:__
InfluxDB 2.x supports Read-Only InfluxQL. But currently, the golang client library does not seem to support it. This proposal is to add this functionality to the client library.

__Current behavior:__
The current golang client library only support querying through FluxQL.

__Desired behavior:__
There should be some functions available that allow querying through InfluxQL.

__Use case:__
This feature supports the older golang code-bases that still uses InfluxQL for querying and producing deliverables. With this feature, they can migrate to this newer client library quite easily, since all the other functionalities are backward compatible. This will help to migrate to Influx 2.x from an earlier release.

**Comment by Yordroid** [comment]
Is it supported now?

**Comment by powersj** [comment]
Hi,

Additional work on this library has stopped, except for issues or other maintenance. 

The v1 golang library can continue to be used for influxql support via v1 auth. If using the new IOX backed influxdb, the [v3 library](https://github.com/InfluxCommunity/influxdb3-go) supports both sql and influxql.
