### ISSUE TITLE
Retries cause metrics payload to duplicate

### ISSUE THREAD

**Issue by GeorgeMac** [influxdata/influxdb-client-go#39]
Due to the where the `goto` statement is placed, in the event of a retry the metrics are encoded again to the same buffer. This leads to duplicate metrics in the event of retries.

https://github.com/influxdata/influxdb-client-go/blob/0d5eea1af5d39d202fc0e5ea16136363026749b1/write.go#L38-L48

**Comment by docmerlin** [comment]
@GeorgeMac we really need to rip the retry code out of the client.write.    That write shouldn't retry but should be a bit lower level, and error when something goes wrong.  If people want automatic retries, one of the buffered writer should be used.
