### ISSUE TITLE
Better diagnosis for unexpected error writing points to database: engine: field type conflict

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb-client-go#396]
Using the async `WriteAPI` and `Errors()` channel, when above error happens it is impossible to relate this to the originating write. It would be nice if the error type could expose additional information.

**Comment by bednar** [comment]
Hi @andig,

thanks for using our client. 

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Regards

**Comment by andig** [comment]
Happy to take a look, but I'd need pointers where this error is actually being generated?

**Comment by bednar** [comment]
Just search `w.errCh <- err` in `write.go` and here https://github.com/influxdata/influxdb-client-go/blob/52afd676229af18dc383dc7b7a340f2d8f562dbe/api/writeAPIBlocking.go#L92 for `writeAPIBlocking.go`.

**Comment by andig** [comment]
I don't think that's particularly helpful. The actual writes are done in the server. The client parses the result here: https://github.com/influxdata/influxdb-client-go/blob/master/api/http/service.go#L174. If we want more detail we need to make sure that the server provides that detail. So maybe I should reopen this in the database repo?

**Comment by bednar** [comment]
> If we want more detail we need to make sure that the server provides that detail. So maybe I should reopen this in the database repo?

You're right; if the detailed information you need isn't available in the current server response, then the issue might be more about enhancing the server's capabilities or modifying how it generates responses. Opening the issue in the database repository would be the correct course of action to discuss and potentially implement the necessary changes. I had initially assumed the existing server response contained the information you needed, but just needed to be exposed or utilized more effectively. Please proceed with opening the issue in the database repo.

**Comment by andig** [comment]
@bednar could you just "transfer" the issue to the db repo? Then we also have the history why this isn't a client topic. Thank you :)
