### ISSUE TITLE
Concept: Metric vs Measurement

### ISSUE THREAD

**Issue by zhulongcheng** [influxdata/influxdb-client-go#40]
Docs, Fluxlang, and InfluxDB's TSDB all use the concept of `Measurement`, rarely use the concept of `Metric`.

Now using the concept of `Metric` in the go client may be confusing to users. 

https://github.com/influxdata/influxdb-client-go/blob/0d5eea1af5d39d202fc0e5ea16136363026749b1/models.go#L9-L30

**Comment by GeorgeMac** [comment]
@stuartcarnie makes sense to me. The go client makes use of github.com/influxdata/line-protocol library where it inherits the the name `Metric` from.
Would you see us changing the line-protocol library first? or do you see it as this clients job to present a `Measurement` type which gets adapted to the line protocol `Metric` type?

**Comment by GeorgeMac** [comment]
Sorry zenhub confused me. @zhulongcheng you reported this not stuart.

**Comment by GeorgeMac** [comment]
cc @docmerlin thoughts?

**Comment by docmerlin** [comment]
@GeorgeMac other than a different name, what would be different between Metric and Measurement?

**Comment by GeorgeMac** [comment]
I assume nothing. At first I wondered if there was some semantic difference. Now I think this is just a name change to be inline with documentation.

**Comment by GeorgeMac** [comment]
Perhaps the term `Point` makes more sense than `RowMetric` here also. But I may be mistaken.

**Comment by andig** [comment]
Imho Measurement is a term from the docs and hence important. Point is only known on programmer side.

**Comment by vlastahajek** [comment]
The library uses [Point](https://github.com/influxdata/influxdb-client-go/blob/master/point.go#L15) for representing single row of written data since version 1.0.0. It is consistent with [other InfluxDB 2 clients](https://v2.docs.influxdata.com/v2.0/reference/api/client-libraries/)
