### ISSUE TITLE
Such a single API sub-client instance can be used concurrently.The performance of the client differs significantly from that of the Inch tool?

### ISSUE THREAD

**Issue by songzhilai** [influxdata/influxdb-client-go#401]
__Proposal:__
True support for concurrent writing.

__Current behavior:__
The test result using inch tool is：70w pt/sec
But using client can only reach 15w

__Desired behavior:__
Concurrent writing can be configured through parameters.

__Use case:__
<img width="1595" alt="image" src="https://github.com/influxdata/influxdb-client-go/assets/18528428/1bd7d814-b991-4c65-987c-130d7e91861b">

```[tasklist]
### Tasks
```

**Comment by vlastahajek** [comment]
Hi @songzhilai,
to clarify: Do you mean you achieved the above-written result using the default parameters for `inch` and using the same data sin your test with this library?

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
