### ISSUE TITLE
Documentation required on how to enablebatching on WriteAPIBlocking

### ISSUE THREAD

**Issue by harishav** [influxdata/influxdb-client-go#407]
Hi Team, 

We are using WriteAPIBlocking for our usecase and the initializing logic goes as below. 

```
client := influxdb2.NewClient(tsDBHost, tsToken)
writeAPIClient := client.WriteAPIBlocking(tsDBOrg, tsDBBucket)
```

Now i wanted to enable batching, as per docs i need to do something like below, 
`writeAPIClient.EnableBatching()`

And then to control the batchSize, its mentioned to specify write.Options(), but we couldn't understand on how to pass the writeOptions and couldn't find any example around that. Can you help on how to enable batching passing the required options ?? 

Thanks!

**Comment by bednar** [comment]
Hi @harishav,

batching is enabled by default, the `writeAPIClient.EnableBatching()` is unnecessary. You can configure batch size by: 

```golang
 client := influxdb2.NewClientWithOptions("http://localhost:8086", "my-token",
        influxdb2.DefaultOptions().SetBatchSize(20))
```

For more info see:

- https://github.com/influxdata/influxdb-client-go?tab=readme-ov-file#non-blocking-write-client

Best Regards
