### ISSUE TITLE
QueryCSV panic

### ISSUE THREAD

**Issue by NigelZHANG** [influxdata/influxdb-client-go#42]
![image](https://user-images.githubusercontent.com/17746687/63143186-a407bb00-c01f-11e9-8ceb-d54489cf4697.png)

in query.go line 37, it will panic if resp is nil, because you use defer function to close resp body.
defer function should be follow the error, like this:
![image](https://user-images.githubusercontent.com/17746687/63143159-93574500-c01f-11e9-94fa-a96c2deb0839.png)

**Comment by GeorgeMac** [comment]
Fixed in https://github.com/influxdata/influxdb-client-go/pull/43
