### ISSUE TITLE
go get -u runs berserk

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb-client-go#44]
Consider this- takes almost a hundred dependencies:

    ❯ mkdir foo && cd foo

    ~/foo
    ❯ go mod init foo
    go: creating new go.mod: module foo

    ~/foo
    ❯ go get -u github.com/influxdata/influxdb-client-go@develop
    go: finding github.com/influxdata/influxdb-client-go develop
    go: finding github.com/influxdata/tdigest latest
    go: finding github.com/influxdata/line-protocol latest
    go: finding golang.org/x/crypto latest
    go: finding golang.org/x/sync latest
    go: finding github.com/andreyvit/diff latest
    go: finding gonum.org/v1/netlib latest
    go: finding golang.org/x/tools latest
    go: finding golang.org/x/exp latest
    go: finding github.com/pkg/term latest
    go: finding golang.org/x/net latest
    go: finding github.com/apache/arrow/go/arrow latest
    go: finding golang.org/x/sys latest
    go: finding gopkg.in/check.v1 latest
    go: finding gonum.org/v1/gonum latest
    go: finding github.com/remyoudompheng/bigfft latest
    go: finding golang.org/x/mobile latest
    go: finding github.com/kevinburke/ssh_config latest
    go: finding github.com/BurntSushi/xgb latest
    go: finding github.com/alecthomas/units latest
    go: finding github.com/jbenet/go-context latest
    go: finding golang.org/x/image latest
    go: finding github.com/anmitsu/go-shlex latest
    go: finding github.com/alcortesm/tgz latest
    go: finding github.com/blakesmith/ar latest
    go: finding github.com/alecthomas/template latest
    go: finding golang.org/x/xerrors latest
    go: finding golang.org/x/oauth2 latest
    go: finding github.com/jpillora/backoff latest
    go: finding github.com/eapache/go-xerial-snappy latest
    go: finding github.com/aybabtme/rgbterm latest
    go: finding github.com/armon/consul-api latest
    go: finding github.com/flynn/go-shlex latest
    go: finding github.com/aphistic/golf latest
    go: finding github.com/mattn/go-tty latest
    go: finding github.com/tj/assert latest
    go: finding github.com/smartystreets/go-aws-auth latest
    go: finding github.com/campoy/unique latest
    go: finding gopkg.in/tomb.v1 latest
    go: finding github.com/jmespath/go-jmespath latest
    go: finding contrib.go.opencensus.io/exporter/aws latest
    go: finding google.golang.org/genproto latest
    go: finding gonum.org/v1/plot latest
    go: finding github.com/golang/freetype latest
    go: finding github.com/ajstarks/svgo latest
    go: finding github.com/GoogleCloudPlatform/cloudsql-proxy latest
    go: finding github.com/golang/glog latest
    go: finding github.com/tmc/grpc-websocket-proxy latest
    go: finding github.com/xdg/scram latest
    go: finding golang.org/x/lint latest
    go: finding github.com/coreos/go-systemd latest
    go: finding golang.org/x/time latest
    go: finding github.com/tj/go-kinesis latest
    go: finding github.com/mgutz/ansi latest
    go: finding github.com/jstemmer/go-junit-report latest
    go: finding github.com/coreos/pkg latest
    go: finding github.com/mattn/go-ieproxy latest
    go: finding github.com/google/pprof latest
    go: finding github.com/codahale/hdrhistogram latest
    go: finding github.com/xiang90/probing latest
    go: finding github.com/golang/groupcache latest
    go: finding github.com/kr/logfmt latest
    go: finding github.com/tj/go-elastic latest
    go: finding github.com/dgryski/go-sip13 latest
    go: finding github.com/prometheus/client_model latest
    go: finding github.com/armon/go-socks5 latest
    go: finding github.com/mwitkow/go-conntrack latest
    go: finding github.com/ruudk/golang-pdf417 latest
    go: finding github.com/modern-go/concurrent latest
    go: finding github.com/rcrowley/go-metrics latest
    go: finding github.com/streadway/amqp latest
    go: finding istio.io/gogo-genproto latest
    go: downloading github.com/influxdata/influxdb-client-go v0.0.2-0.20190805165203-23da33b60c81
    go: extracting github.com/influxdata/influxdb-client-go v0.0.2-0.20190805165203-23da33b60c81

**Comment by GeorgeMac** [comment]
Thank you for bringing this to our attention @andig 👋

While this client shouldn't have many direct dependencies, as it is for the most part a wrapper around a net/http client, we have some dependencies on tools like our own flux language and therefore the flux repo. This sadly does bring a lot of other transitive dependencies along with it.

We currently depend upon go modules and specifically the `go mod tidy` command to ensure the minimal set of dependencies is required to build this project. This is enforced at the point of integration via circleci: https://github.com/influxdata/influxdb-client-go/blob/develop/.circleci/config.yml#L27 .

Short of changing our dependency management tool, refactoring or replacing our dependencies such that we can import more minimal set of dependencies, I am unsure how best to change this right now. I could be mistaken though.

**Comment by andig** [comment]
Understood. I was wobdering- if flux is the cause- if splitting flux api (if rhats what you need) into its own module would work?

**Comment by GeorgeMac** [comment]
I am a little unclear on the full extent of the pieces of flux that we need in this project (off the top of my head at least), but in theory the pieces of flux we need may be isolatable and broken off the flux repo into a smaller shared module.
Given this were possible it may still be unfavorable in the long run to have to maintain that as a separate entity. It will raise larger questions around ownership and lifecycle of that module. How would we manage releases and versioning of that module?
Not to say that ultimately this is isn't the way we want to go. I am just illustrating the potential for added complexity which I imagine the wider organisation wouldn't find valuable at this time. Particularly given the motivation was to simply make this client more lean. I don't speak for everyone though :D

**Comment by docmerlin** [comment]
@andig the flux dependencies and most of the other dependencies all except the standard library and github.com/influxdata/line-protocol are test dependencies, and you don't need them for building.  I wish go mod had a separate thing for test dependencies, maybe we should ship them off into a separate package, with its own mod file, hrm.

Flux for example, we use as a test dep, to make sure we are matching the spec properly.

**Comment by GeorgeMac** [comment]
Just chatted with @docmerlin and he made a great suggestion. Since our test suite is the only part which depends on flux. It may be possible to separate the test into a seperate sub module with its own go.mod file. Removing it from the main module file used for the client itself.
This would greatly reduce the dependencies required to import this client. So it may be possible after all 👍

**Comment by andig** [comment]
If you don‘t need to test internals- which would require rhe test files to be in the same package- that should work 👍🏻

**Comment by andig** [comment]
Go 1.13 has just been released and contains improvements that might be important:

> In module-aware mode, go get with the -u flag now updates a smaller set of modules that is more consistent with the set of packages updated by go get -u in GOPATH mode. go get -u continues to update the modules and packages named on the command line, but additionally updates only the modules containing the packages imported by the named packages, rather than the transitive module requirements of the modules containing the named packages.

I‘ll double-check its behavior when back home.

**Comment by andig** [comment]
I can confirm that go 1.13 looks much better:

    ❯ go get -u github.com/influxdata/influxdb-client-go@develop
    go: finding github.com develop
    go: finding github.com/influxdata develop
    go: finding github.com/influxdata/influxdb-client-go develop
    go: downloading github.com/influxdata/influxdb-client-go v0.0.2-0.20190904105117-88077c0e417b
    go: extracting github.com/influxdata/influxdb-client-go v0.0.2-0.20190904105117-88077c0e417b
    go: finding github.com/influxdata/line-protocol latest

From that perspective I'm closing here.
