### ISSUE TITLE
Implement SignIn()

### ISSUE THREAD

**Issue by GeorgeMac** [influxdata/influxdb-client-go#47]
Closes #45 

All actions for influxdb 2.0 need to be authenticated either via a token or session (and in the future JWT).

Client currently only supports `Setup()` which completes onboarding procedure for new user / org / bucket creation. Calling this does retrieve a session token and subsequently uses it for auth. However, this is only suitable once per unique user + org + bucket combo.

We should leverage the `/signin` basic auth api call when username is provided via `WithUsernameAndPassword` and no authentication has been set.

Example:

```go
func (c *Client) SignIn() error {
    c.mu.Lock()
    defer c.mu.Unlock()

    //...
    resp, err := c.do(req)
    // ...
    c.session = token
}

func WithUsernamePassword(username, password string) Option {
    return func(c *Client) {
        c.username = username
        c.password = password
        c.once = sync.Once{}
    }
}

func (c *Client) signIn() {
    c.once.Do(func(){
        if err := c.SignIn(); err != nil {
            c.logger.Error(err)
        }
    })
}

func (c *Client) Write(...) {
    c.signIn()
}
```

Update:

For reference /signin returns session via `Set-Cookie: session=token`

Another Update:

Need to actually use this token as a session cookie. Consider using https://golang.org/pkg/net/http/cookiejar/

**Comment by vlastahajek** [comment]
The duplicate issue for #45.
