### ISSUE TITLE
Add test around gzip responses from influxdb

### ISSUE THREAD

**Issue by GeorgeMac** [influxdata/influxdb-client-go#59]
We should ensure that we handle gziped responses from influxdb in our test suite.

Either via a unit tests or the end to end tests (or even better both).

see: https://github.com/influxdata/influxdb-client-go/pull/56

**Comment by vlastahajek** [comment]
[Such test](https://github.com/influxdata/influxdb-client-go/blob/master/query_test.go#L379) exist since 1.0.0
