### ISSUE TITLE
Option to run arbitrary commands

### ISSUE THREAD

**Issue by pavel-odintsov** [influxdata/influxdb-client-go#66]
Hello!

I'm using "github.com/influxdata/influxdb/client/v2" and I'm quite disappointed to see old client completely removed. 

I like new client but there are some features which aren't available in new one. 

Previously, you had option to run arbitrary commands using client:
``` 
    q := influx_client.Query{
        Command:  cmd,
        Database: database_name,
    }
    if response, err := influx_client_connection.Query(q); err == nil {
        res = response.Results
    } 
```

Unfortunately, it's not possible with new client.

How can I implement it?

Thank you!

**Comment by vlastahajek** [comment]
@pavel-odintsov, InfluxDB 2 has a completely different approach for management tasks. 
There is a [rich REST API](https://v2.docs.influxdata.com/v2.0/api/) exposed by the server, which will be made accessible by this client library subsequently in further releases.  Lastest v1.2.0 added Authorizations, Organization and Users APIs. 
The next version will have Buckets, Delete and some others.
