### ISSUE TITLE
Help with QueryCSV

### ISSUE THREAD

**Issue by amaurybrisou** [influxdata/influxdb-client-go#67]
Hello,
I'd like to know if this snippet is a correct way to use the QueryCSV function:
```
q := fmt.Sprintf(
	`from(bucket: "%s")
		|> range(start: -1h)
		|> filter(fn: (r) => r._measurement == "occupation" and r._field == "%s")
		|> last()`, me.c.InfluxDB.PullBucket, sensor)

response, err := me.cli.QueryCSV(
	context.Background(),
	q,
	me.c.InfluxDB.Org,
	[]int{},
)
```

I'm having this error ```flux: unsupported type: is not supported to generate flux, try a map or a struct with public keys``` at the moment.

Thank you.

**Comment by jadamroth** [comment]
Thank you for the code demonstrating how to unmarshall the returned data. The lack of examples for queries is annoying
