### ISSUE TITLE
client.QueryCSV fails for multiple yields

### ISSUE THREAD

**Issue by aelango97** [influxdata/influxdb-client-go#68]
I have a flux query which returns 2 yields in a single script as follows:
(Assuming all the values are sent)
```flux
workbench = from(bucket: "test")
  |> range(start: v.timeStart, stop: v.timeEnd)
  |> filter(fn: (r) => r._measurement == "mem")
  |> filter(fn: (r) => r.host == v.host)

count = workbench
    |> count()
    |> yield(name:"count")
data = workbench
    |> limit(n: v.limit, offset : v.offset)
    |> sort(columns: ["_time"], desc: v.isDescending)
    |> yield(name:"data")
```

From the resulting query I get 2 series in the HTTP request. But the package fails to 
read the second series returning the error `record on line 61: wrong number of fields`. So I tried setting the csvreader with `FieldsPerRecord` as -1 (as per [this](https://golang.org/pkg/encoding/csv/#Reader)). It fails for that too. Need help.

**Comment by russorat** [comment]
@aelango97 thanks! we will take a look.

**Comment by aelango97** [comment]
@russorat , My apologies. When `FieldsPerRecord` is set to -1 it did work.<sup>[1](#1)</sup>
But doesn't make any sense as far the usage is concerned. In a for loop, there is no way to get at what table ID the current cursor is in. For example if I'm able to get the result column, before calling `Decode`, I'll be able call `Decode` with the right struct. I did implement my own version of Decoder with that functionality, which meant I had to read the whole CSV into `[][]string`, instead of buffered read which is not a good idea for larger data sets. Hopefully this helps.

<a id="1">**1**</a>: I used `map[string]interface{}`

**Comment by docmerlin** [comment]
@aelango97 thanks for bringing this to my attention, we will get to work on it.
