### ISSUE TITLE
Support base64Binary

### ISSUE THREAD

**Issue by docmerlin** [influxdata/influxdb-client-go#69]
Flux added a base64Binary type.
The client should support this.

Information for the type:
https://github.com/influxdata/flux/blob/master/docs/SPEC.md#annotations

query.go will need to be updated so that type can be properly unmarshaled.

internal/ast/ast.go will also need to be updated to support this.

**Comment by vlastahajek** [comment]
The `base64Binary type is supported since v1.0.0:
- [code](https://github.com/influxdata/influxdb-client-go/blob/master/query.go#L369)
- [test](https://github.com/influxdata/influxdb-client-go/blob/master/query_test.go#L379)
