### ISSUE TITLE
CSVReader incorrectly maps rows and column names

### ISSUE THREAD

**Issue by ammmir** [influxdata/influxdb-client-go#74]
A query with the resulting CSV:

```csv
,result,table,_start,_stop,uptime,_time
,_result,0,2020-01-27T05:04:48.70477677Z,2020-01-27T17:04:48.70477677Z,0.5454545454545454,2020-01-27T06:00:00Z
,_result,0,2020-01-27T05:04:48.70477677Z,2020-01-27T17:04:48.70477677Z,1,2020-01-27T07:00:00Z
```

yields incorrect row and column name information:

    ColNames: [result table _start _stop uptime _time]
    Row: [  0 2020-01-27T04:49:51.607050038Z 2020-01-27T16:49:51.607050038Z 0 2020-01-27T05:00:00Z]

It seems that the preceding comma creates an extra empty element in the Row slice, offsetting each row by 1 index.

**Comment by russorat** [comment]
@ammmir thanks for the issue. we have a big update to this client lib coming soon and we will make sure this gets addressed.

**Comment by vlastahajek** [comment]
@ammmir, a new version of the client use a different representation of flux query result which has not this problem.
