### ISSUE TITLE
Can't set precision

### ISSUE THREAD

**Issue by live-wire** [influxdata/influxdb-client-go#75]
According to the [docs](https://v2.docs.influxdata.com/v2.0/write-data/ ): the API supports setting precision. But, I couldn't find any function exposed for doing the same here :(

Does this precision need to be set at a bucket level? Any more tips would be appreciated. @russorat

**Comment by russorat** [comment]
@live-wire thanks for opening this. Looks like it is not possible to set this yet. We are working on an overhaul of this lib in the coming weeks and will incorporate this into that update.

**Comment by vlastahajek** [comment]
@live-wire, we've just released a new version with updated API.  
The setting of write precision is available in the [Options](https://github.com/influxdata/influxdb-client-go/blob/master/options.go#L13) object.
