### ISSUE TITLE
Authorization create/delete example with SDK

### ISSUE THREAD

**Issue by gitirabassi** [influxdata/influxdb-client-go#82]
I'd like to be able to generate tokens and expire them using vault. 

I contributed the influxdb V1 integration to Vault almost a year ago 
https://www.vaultproject.io/docs/secrets/databases/influxdb/

It's time to be able to do the same with Influxdb V2 but I'm able to work with the new SDK. can I get an example of workable creation of a new token?

**Comment by vlastahajek** [comment]
@gitirabassi, this is not implemented yet, however we will start working on this soon.

**Comment by vlastahajek** [comment]
Authorization API added via #96
