### ISSUE TITLE
Is it the client's purpose to handle the whole HTTP API?

### ISSUE THREAD

**Issue by ppff** [influxdata/influxdb-client-go#84]
We're writing a small terraform provider for influx v2 to automate the creation of buckets, etc. Hence, we're trying to use this client as much as possible.

There's already a file for the `setup/` route, but only for this one. Do you intend to add support for all other routes, and should we contribute to that, or should we write our own http requests because the goal of the client is simply to allow handy read/writes (and secondary operations such as setup)?

**Comment by russorat** [comment]
@ppff thanks! we are very close to having an updated client that should have the same capabilities as the other client libraries. We will update this issue when it has been updated.

**Comment by vlastahajek** [comment]
@ppff, what additional routes would your provider need? 
Currently (v1.3.0), the supported API are:

- Authorizations
- Buckets
- Health
- Labels
- Organizations
- Query
- Ready
- Setup
- Users
- Write

**Comment by ppff** [comment]
I'm glad to see you covered all this pretty quickly! We did it on our side in the meantime, we can now ditch our fork.
