### ISSUE TITLE
Please add a godoc link to the readme

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb-client-go#85]
..or provide API documentation here.

**Comment by andig** [comment]
Please also add an example how to use query parameters if these are still supported. Such is already missing from the v1 docs (https://github.com/influxdata/influxdb1-client/issues/20). It would be nice if the client could be used for more than creating data sinks ;)

**Comment by vlastahajek** [comment]
Added doc link to the readme. Query params are not supported yet, but when added there will be an example.
