### ISSUE TITLE
arbitrary " added to tag fields

### ISSUE THREAD

**Issue by davidgs** [influxdata/influxdb-client-go#87]
I'm inserting large amounts of data via the golang library, and I'm seeing arbitrary trailing `"` characters added to some of the tag fields. 

I've done step-by-step debugging to ensure that the `"` is not there when the `influxdb.Metric()` object is built and submitted to the influxdb Client `write` method, but the quotes still show up (not on all tags, just some). 

`myMetrics = []influxdb.Metric{
	influxdb.NewRowMetric(
		map[string]interface{}{"confirmed": confirmed,
			"deaths":    dead,
			"recovered": recovered,
			"lat":       latitude,
			"lon":       longitude},
		meas,
		map[string]string{
			"state_province": Case.Province,
			"country_region": Case.Country,
			"s2_cell_id":     cell,
			"last_update":    stringTime,
		},
	t),
}`

I've verified that `Case.Province` does NOT have extra trailing quotes, I've run the string through `strings.Trim()` as well as `strings.Replace()` to ensure the `"` character is not there, but it still ends up in the database.

**Comment by vlastahajek** [comment]
Hi @davidgs, a new version with updated API was released, could you, please, check it? 
However, encoding data to line protocol remained the same, but the underlying lib was updated.
