### ISSUE TITLE
writer keep return last error without request influxdb API

### ISSUE THREAD

**Issue by XSAM** [influxdata/influxdb-client-go#88]
Hi, I use the `PointWriter` to write metrics with an underlying buffer to influxdb.

Here is the code

```go
client, _ := influxdb.New(config.Endpoint, config.Token)
writer := influxdb_writer.New(client, config.Bucket, config.Organization)
```

Then I got something weird. When the writer returns an error from influxdb (for instance, exceeded rate limit), then every time the writer writes, it returns the last error, even the influxdb service back to normal. And there is no more network connection with influxdb service.

Then I found this code:
https://github.com/influxdata/influxdb-client-go/blob/fb46d51c708744168277abfa8a6e09443d948b56/writer/point.go#L103-L118

Once the `p.err` is an error, there is no way that it will invoke the underlying writer to write metrics. And there are many places in code like that.

I have no idea what's going on. And I miss something?

**Comment by russorat** [comment]
@XSAM thank you for this issue. We are in the process of replacing this client lib with a new version to address many of these issues. Should be here next week. We will update this issue when it's ready.

**Comment by XSAM** [comment]
Cool! that would be great.

**Comment by vlastahajek** [comment]
@XSAM , we've released a new version with updated API and internals.  Could you, please, check it?

**Comment by XSAM** [comment]
Thanks! That works for me. Closing.
