### ISSUE TITLE
Can't write float values to Influx Cloud

### ISSUE THREAD

**Issue by Emil9999** [influxdata/influxdb-client-go#93]
The following doesn't work for me:
```
p := influxdb2.NewPoint("sensor-data",
		map[string]string{"id": "1"},
		map[string]interface{}{"temp": 45.5,"lightIntensity": 120},
		time.Now())
```
Only the lightIntensity is written to the cloud, any **float** value does not work. Issue only came up with the newest client.

**Comment by vlastahajek** [comment]
Did you get any error from write api? Errors are always written to default logger (stdout).
Also, can you show code for the previous version of the library, please?
I suspect, there could be a field type conflict.

**Comment by Emil9999** [comment]
@vlastahajek Thanks for the fast reply! No errors whatsoever, again the int value is actually written. 
This is the code from the old version: 
```
p:= []influxdb.Metric{
		influxdb.NewRowMetric(
			map[string]interface{}{
				"temp":          45.5,
				"lightIntensity": 120,
			},
			"sensor-data",
			map[string]string{"id": "1"},
			time.Now()),
```

**Comment by vlastahajek** [comment]
@Emil9999, great, it finally works for you! It is indeed weird that you haven't got any error. InfluxDB 2 returns usually error when there is field type conflict. You should see something like: ` [E]! Write error: internal error: unexpected error writing points to database: partial write: series type mismatch: already Integer but got Float dropped=1`
