### ISSUE TITLE
Unconfigurable timeout causing long queries to fail.

### ISSUE THREAD

**Issue by allstream** [influxdata/influxdb-client-go#94]
https://github.com/influxdata/influxdb-client-go/blob/b0a03791e73d9d40dfb895b2370a62498261fb4d/client.go#L85

The Line above is unconfigurable through the provided API-Interface and it essentially seems to force all queries to be <=20 seconds. Am I missing something or is this configurable? I can't seem to get around it.

I constantly get the error:
`Post "https://localhost/api/v2/query?org=testing_queries": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by vlastahajek** [comment]
@allstream, unfortunately, it is not configurable now.  We will make this configurable in the next version. You should be able to work-around this by manually changing the library sources in the package folder.
On the other hand, a query shouldn't take so long. Is the server under a heavy load?
Or, are you expecting a lot of rows returned, or do you use some data manipulation functions on a lot of rows?

**Comment by allstream** [comment]
@vlastahajek Thanks for the quick response. To answer your question about heavy load / lots of results:
I've been doing some benchmarks since I'm looking at various TSDB's to see what matches our organizations needs and thought that this was a strange issue. The query would return a lot of results, wouldn't say it's heavy load.

**Comment by vlastahajek** [comment]
@allstream, I've managed to add the update for this in the version we've released today. Check new version, please, it works for you. The default timeout remained the same, but you can change it easily:
```go
client := influxdb2.NewClientWithOptions("http://localhost:9999", "token", DefaultOptions().SetHttpRequestTimeout(50))
 ```

**Comment by allstream** [comment]
@vlastahajek Got the new version and changed my code and it's all working great! took 24 seconds to run my query. Thanks a lot!
